### Read Entitysets via OData V4
http://localhost:4004/admin/
Authorization: Basic YWRtaW46
### Read Entitysets via OData V2
http://localhost:4004/v2/admin/
Authorization: Basic YWRtaW46

### Read Authors via OData V4
http://localhost:4004/admin/Authors
Authorization: Basic YWRtaW46

### Read Authors via OData V2
http://localhost:4004/v2/admin/Authors
Authorization: Basic YWRtaW46

### Read Roles via OData V2
http://localhost:4004/v2/admin/Roles
Authorization: Basic YWRtaW46

### Read Orders via OData V2
http://localhost:4004/v2/admin/Orders
Authorization: Basic YWRtaW46

### Read Order Items via OData V2
http://localhost:4004/v2/admin/Orders(ID=guid'7e2f2640-6866-4dcf-8f4d-3027aa831cad',IsActiveEntity=true)/Items
Authorization: Basic YWRtaW46


### Read BusinessObjects assigned to Roles via OData V2
http://localhost:4004/v2/admin/Roles(ID=guid'1e50a05d-aa09-4bd2-b2a5-0d096adb7b8c',IsActiveEntity=true)/BusinessObjects
Authorization: Basic YWRtaW46

### Read Roles Expanded to  via OData V2
http://localhost:4004/v2/admin/Role?$expand=BusinessObjects,Users
Authorization: Basic YWRtaW46

