### Read Metadata via OData V4
GET http://localhost:4004/admin/$metadata
Authorization: Basic admin:

### Read Metadata via OData V2
GET http://localhost:4004/v2/admin/$metadata
Authorization: Basic admin:

### Read Entitysets via OData V4
GET http://localhost:4004/admin/
Authorization: Basic admin:
### Read Entitysets via OData V2
GET http://localhost:4004/v2/admin/
Authorization: Basic admin:

### Read Authors via OData V4
GET http://localhost:4004/admin/Authors
Authorization: Basic admin:

### Read Authors via OData V2
GET http://localhost:4004/v2/admin/Authors
Authorization: Basic admin:

### Read Books via OData V4
GET http://localhost:4004/admin/Books
Authorization: Basic admin:

### Read Books via OData V2 by admin and expand to author
GET http://localhost:4004/v2/admin/Books?$expand=author
Authorization: Basic admin:

### Update Book via OData V2 by admin
PUT http://localhost:4004/v2/admin/Books(1)
Authorization: Basic admin:
Content-Type: application/json

{ "stock": 15 }

### Read Books via OData V4 by admin
GET http://localhost:4004/admin/Books
Authorization: Basic admin:

### Update Book via OData V4 by admin
PUT http://localhost:4004/admin/Books(1)
Authorization: Basic admin:
Content-Type: application/json

{ 
  "createdAt": "2020-10-13T13:30:41.500Z"
}
### Read Approval via OData V2 by admin
GET http://localhost:4004/v2/admin/Approval
Authorization: Basic admin:

### Read Roles via OData V2
GET http://localhost:4004/v2/admin/Roles
Authorization: Basic admin:

### Read Orders via OData
GET http://localhost:4004/admin/Orders?$top=1&$expand=Items
Authorization: Basic admin:

### Read Orders via OData V2
GET http://localhost:4004/v2/admin/Orders
Authorization: Basic admin:

### Read Order Items via OData V2
GET http://localhost:4004/v2/admin/Orders(ID=guid'7e2f2640-6866-4dcf-8f4d-3027aa831cad',IsActiveEntity=true)/Items
Authorization: Basic admin:

### Read BusinessObjects assigned to Roles via OData V2
GET http://localhost:4004/v2/admin/Roles(ID=guid'1e50a05d-aa09-4bd2-b2a5-0d096adb7b8c',IsActiveEntity=true)/BusinessObjects
Authorization: Basic admin:

### Read Roles Expanded to  via OData V2
GET http://localhost:4004/v2/admin/Roles?$expand=BusinessObjects,Users
Authorization: Basic admin:

### Read Roles Expanded to  via OData V4
GET http://localhost:4004/admin/Roles?$expand=BusinessObjects,Users
Authorization: Basic admin:

### Read Users Expanded to via OData V4 - 
GET http://localhost:4004/admin/Users?$expand=address
Authorization: Basic admin:

### Read Users Expanded to via OData V2
### Results in:
### An error occurred during serialization of the entity collection. An error occurred during serialization of the entity with the following key(s): username: douglas. The provided data does not fit the type of the navigation property: address.
GET http://localhost:4004/v2/admin/Users?$expand=address
Authorization: Basic admin: