###
GET http://localhost:4004/agreement/
###
GET http://localhost:4004/agreement/Agreement
###
GET http://localhost:4004/agreement/Agreement
  ?$expand=items($expand=pricings($expand=status))
###
GET http://localhost:4004/agreement/ChangeSet
  ?$expand=agreementItemPricings($expand=status),changeSetToAgreements
###
GET http://localhost:4004/agreement/ChangeSetSearch
  ?$count=true
  &$expand=changeSetToAgreements($expand=agreement)
  &$filter=agreementItemPricings/any(d:d/status_code eq 'NEW') or agreementItemPricings/any(d:d/status_code eq 'CLOSED')
###
GET http://localhost:4004/agreement/AgreementChangesAndStatus
###
GET http://localhost:4004/agreement/ChangeSetToAgreementSearch
###
GET http://localhost:4004/agreement/AgreementItemPricing
  ?$count=true
  &$select=ID,validFrom,validTo
###
GET http://localhost:4004/v2/agreement/AgreementItemPricing
  ?$inlinecount=allpages
  &$select=ID,validFrom,validTo
### View with parameters
###
GET http://localhost:4004/agreement/AgreementItemPricingForKeyDate(keyDate=2021-10-15)/Set
  ?$count=true
###
GET http://localhost:4004/v2/agreement/$metadata
###
GET http://localhost:4004/v2/agreement/AgreementItemPricingForKeyDate(keyDate=2021-10-15)/Set
  ?$inlinecount=allpages
### Mimic ABAP Endpoint
###
GET http://localhost:4004/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/
###
GET http://localhost:4004/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/$metadata
###
GET http://localhost:4004/v2/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/$metadata
###
GET http://localhost:4004/v2/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/Z_C_AItemPricingForKeyDate(keyDate=2021-10-15)/Set
###
GET http://vhcala4hci:50000/sap/opu/odata/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/Z_C_AItemPricingForKeyDate(keyDate=datetime%272022-06-17T00%3a00%3a00%27)/Set
  ?sap-client=001
#  &$expand=Parameters
Authorization: Basic {{$dotenv abap_username}}:{{$dotenv abap_password}}
Accept: application/json
###
GET http://vhcala4hci:50000/sap/opu/odata/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/Z_C_AItemPricingForKeyDateSet(keyDate=datetime'2022-06-17T00%3A00%3A00',ID='90db54bc-383b-4267-bca3-1252aafe1168')
  ?sap-client=001
Authorization: Basic {{$dotenv abap_username}}:{{$dotenv abap_password}}
Accept: application/json
###
GET http://vhcala4hci:50000/sap/opu/odata/sap/Z_C_AITEMPRICINGFORKEYDATE_CDS/Z_C_AItemPricingForKeyDateSet(keyDate=datetime'2022-06-17T00%3A00%3A00',ID='90db54bc-383b-4267-bca3-1252aafe1168')/Parameters
  ?sap-client=001
Authorization: Basic {{$dotenv abap_username}}:{{$dotenv abap_password}}
Accept: application/json
