-- SQLite
-- Query generated by @sap/cds: 4.4.6
-- resulting in Error: SQLITE_ERROR: no such column: a.ASSOC_Book_BusinessValidFrom
SELECT a.BusinessValidFrom AS "a_BusinessValidFrom",
  a.BusinessValidTo AS "a_BusinessValidTo",
  a.Role AS "a_Role",
  a.ASSOC_Book_ID AS "a_ASSOC_Book_ID",
  a.ASSOC_Author_ID AS "a_ASSOC_Author_ID",
  b.createdAt AS "b_createdAt",
  b.modifiedAt AS "b_modifiedAt",
  b.ID AS "b_ID",
  b.BusinessValidFrom AS "b_BusinessValidFrom",
  b.BusinessValidTo AS "b_BusinessValidTo",
  b.title AS "b_title",
  b.descr AS "b_descr",
  b.stock AS "b_stock",
  b.price AS "b_price",
  b.semanticURLtoAuthor AS "b_semanticURLtoAuthor",
  b.weight AS "b_weight",
  b.height AS "b_height",
  b.width AS "b_width",
  b.visible AS "b_visible",
  b.releaseDate AS "b_releaseDate",
  b.readingTime AS "b_readingTime",
  b.currency_code AS "b_currency_code",
  c.createdAt AS "c_createdAt",
  c.modifiedAt AS "c_modifiedAt",
  c.ID AS "c_ID",
  c.BusinessValidFrom AS "c_BusinessValidFrom",
  c.BusinessValidTo AS "c_BusinessValidTo",
  c.name AS "c_name",
  c.dateOfBirth AS "c_dateOfBirth",
  c.dateOfDeath AS "c_dateOfDeath",
  c.placeOfBirth AS "c_placeOfBirth",
  c.placeOfDeath AS "c_placeOfDeath",
  c.alive AS "c_alive",
  c.country_code AS "c_country_code"
FROM localized_CatalogService_BooksAuthorsAssignment a
  LEFT JOIN localized_CatalogService_Books b ON (
    b.ID = a.ASSOC_Book_ID
    AND b.BusinessValidFrom = a.ASSOC_Book_BusinessValidFrom
    AND b.BusinessValidTo = a.ASSOC_Book_BusinessValidTo
  )
  LEFT JOIN localized_CatalogService_Authors c ON (
    c.ID = a.ASSOC_Author_ID
    AND c.BusinessValidFrom = a.ASSOC_Author_BusinessValidFrom
    AND c.BusinessValidTo = a.ASSOC_Author_BusinessValidTo
  )
ORDER BY a.BusinessValidFrom COLLATE NOCASE ASC,
  a.BusinessValidTo COLLATE NOCASE ASC,
  a.Role COLLATE NOCASE ASC,
  a.ASSOC_Book_ID COLLATE NOCASE ASC,
  a.ASSOC_Author_ID COLLATE NOCASE ASC
LIMIT 100

--- Adjusted to avoid the error
SELECT a.BusinessValidFrom AS "a_BusinessValidFrom",
  a.BusinessValidTo AS "a_BusinessValidTo",
  a.Role AS "a_Role",
  a.ASSOC_Book_ID AS "a_ASSOC_Book_ID",
  a.ASSOC_Author_ID AS "a_ASSOC_Author_ID",
  b.createdAt AS "b_createdAt",
  b.modifiedAt AS "b_modifiedAt",
  b.ID AS "b_ID",
  b.BusinessValidFrom AS "b_BusinessValidFrom",
  b.BusinessValidTo AS "b_BusinessValidTo",
  b.title AS "b_title",
  b.descr AS "b_descr",
  b.stock AS "b_stock",
  b.price AS "b_price",
  b.semanticURLtoAuthor AS "b_semanticURLtoAuthor",
  b.weight AS "b_weight",
  b.height AS "b_height",
  b.width AS "b_width",
  b.visible AS "b_visible",
  b.releaseDate AS "b_releaseDate",
  b.readingTime AS "b_readingTime",
  b.currency_code AS "b_currency_code",
  c.createdAt AS "c_createdAt",
  c.modifiedAt AS "c_modifiedAt",
  c.ID AS "c_ID",
  c.BusinessValidFrom AS "c_BusinessValidFrom",
  c.BusinessValidTo AS "c_BusinessValidTo",
  c.name AS "c_name",
  c.dateOfBirth AS "c_dateOfBirth",
  c.dateOfDeath AS "c_dateOfDeath",
  c.placeOfBirth AS "c_placeOfBirth",
  c.placeOfDeath AS "c_placeOfDeath",
  c.alive AS "c_alive",
  c.country_code AS "c_country_code"
FROM localized_CatalogService_BooksAuthorsAssignment a
  LEFT JOIN localized_CatalogService_Books b ON (
    b.ID = a.ASSOC_Book_ID
  )
  LEFT JOIN localized_CatalogService_Authors c ON (
    c.ID = a.ASSOC_Author_ID
  )
ORDER BY a.BusinessValidFrom COLLATE NOCASE ASC,
  a.BusinessValidTo COLLATE NOCASE ASC,
  a.Role COLLATE NOCASE ASC,
  a.ASSOC_Book_ID COLLATE NOCASE ASC,
  a.ASSOC_Author_ID COLLATE NOCASE ASC
LIMIT 100