### Read BooksAuthorsAssignment
GET http://localhost:4004/catalog/BooksAuthorsAssignment
Authorization: Basic admin:

### Read BooksAuthorsAssignment expand to Book and Author 
GET http://localhost:4004/catalog/BooksAuthorsAssignment?$expand=ASSOC_Book,ASSOC_Author
Authorization: Basic admin: