### Test cds watch bookshop from https://github.com/SAP-samples/cloud-cap-samples

### Read Metadata OData V4
GET http://localhost:4004/public/$metadata
### Read Entities with OData V4
GET http://localhost:4004/public/
###
GET http://localhost:4004/public/Books
  ?$count=true
  #&$expand=genre
#  &$filter=genre/name eq 'Drama'
# Returns:
# Path expressions in query options are not supported on SQLite

###
GET http://localhost:4004/public/Books
  ?$count=true
  &$expand=genre
#  &$filter=genre/all(g:g/name eq 'Drama')

# Returns:
# Property 'all' does not exist in type 'CatalogService.Genres'
###
GET http://localhost:4004/public/Genres