### Request Access Token
# @name requestAccessToken
POST {{$dotenv reporting_tokenendpoint}}/oauth/token
Accept: application/json
Authorization: Basic {{$dotenv reporting_clientid}}:{{$dotenv reporting_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}
&client_id={{$dotenv reporting_clientid}}
&response_type=token
#&login_hint={"origin":"sap.custom"}
### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
@id_token = {{requestAccessToken.response.body.$.id_token}}
###
GET {{$dotenv reporting_url}}/reports/v1/monthlyUsage
Authorization: Bearer {{access_token}}
