### Read Orders via OData
GET http://localhost:4004/catalog/Orders?$expand=Items
Authorization: Basic bob:

### Read Orders via OData
GET http://localhost:4004/catalog/OrderItems
Authorization: Basic bob:

### Create Orders in two steps
POST http://localhost:4004/catalog/Orders
Authorization: Basic bob:
Content-Type: application/json

{
    "OrderNo": "11",
    "CustomerOrderNo": "Order from bob",
    "currency_code": "EUR",
    "Items": [

    ],
    "ShippingAddress":  {
        "street": "Hauptstraße 1",
        "city": "Trostberg"
    }
}

### Create Order Item
POST http://localhost:4004/catalog/Orders(2fe1d720-e4b2-43eb-93be-f5ffe60a762d)/Items
Authorization: Basic bob:
Content-Type: application/json

{
    "book_ID": 201
}

### Read Order as john
GET http://localhost:4004/catalog/Orders
Authorization: Basic john:
Content-Type: application/json

### Create Order as john - using deep insert
POST http://localhost:4004/catalog/Orders
Authorization: Basic john:
Content-Type: application/json

{
    "OrderNo": "10",
    "CustomerOrderNo": "Order from john",
    "currency_code": "EUR",
    "Items": [
        {
            "book_ID": 201
        }
    ],
    "ShippingAddress":  {
        "street": "Hauptstraße 1",
        "city": "Trostberg"
    }
}
### Create Order via Action
POST http://localhost:4004/catalog/submitOrder
Authorization: Basic bob:
Content-Type: application/json

{ "book":201, "amount":5 }
