### Request Access Token
# @name requestAccessToken
POST {{$dotenv cloud_alm_url}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv cloud_alm_clientid}}
&client_secret={{$dotenv cloud_alm_clientsecret}}
&grant_type=client_credentials
&response_type=token
### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}

###
GET {{$dotenv cloud_alm_api}}/imp-cdm-transport-management-api/v1/actions
Authorization: Bearer {{access_token}}
