###
# @name access_token_request
POST {{$dotenv cf_login}}/oauth/token
Accept: application/json;charset=utf8
Authorization: Basic cf:
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}
# &login_hint={"origin":"sap.ids"}
# According to SAP Note https://launchpad.support.sap.com/#/notes/3140806
# currently only supported in Feature Set A
# According to the Roadmap Item "Customer ability to control users and their account access"
# https://roadmaps.sap.com/board?q=idp&range=CURRENT-LAST#;INNO=000D3AAADBCE1EDB9EEDE92DF8DF3E21
# the usage of IAS in Feature Set B should be possible beginning of July 2022
# Using Origin Key origin=sap.default results in:
# The origin provided in the login_hint does not match an active Identity Provider, that supports password grant.
# If you want to use your own IAS tenant, you have to uncomment the following line and maintain the variable origin in your .env file
#&login_hint={"origin":"{{$dotenv origin}}"}

###
@accToken = {{access_token_request.response.body.access_token}}

### List all Organizations
GET {{$dotenv cf_url}}/v3/organizations
Authorization: Bearer {{accToken}}
### Filter Organization by name
GET {{$dotenv cf_url}}/v3/organizations
  ?names=07fc19abtrial
Authorization: Bearer {{accToken}}
### Details of specific Organization
GET {{$dotenv cf_url}}/v3/organizations/{{$dotenv org_id}}
Authorization: Bearer {{accToken}}
###
GET {{$dotenv cf_url}}/v3/spaces
Authorization: Bearer {{accToken}}
###
GET {{$dotenv cf_url}}/v3/spaces/{{$dotenv space_id}}
Authorization: Bearer {{accToken}}
###
GET {{$dotenv cf_url}}/v3/apps
  ?organization_guids={{$dotenv org_id}}
  &space_guids={{$dotenv space_id}}
  &names=bookshop-demo-ui
Authorization: Bearer {{accToken}}
###
GET {{$dotenv cf_url}}/v3/domains
Authorization: Bearer {{accToken}}

###
# Documentation at:
# https://help.sap.com/docs/TRANSPORT_MANAGEMENT_SERVICE/7f7160ec0d8546c6b3eab72fb5ad6fd8/c9905c142cf14aea86fe2451434faed9.html?locale=en-US
GET {{$dotenv cf_deploy}}{{$dotenv cf_deploy_path}}
Authorization: Bearer {{accToken}}

###
GET {{$dotenv cf_deploy}}/public/ping

### CAP
### Read Metadata OData V4
GET http://localhost:4004/odata/v4/admin/readOrganizations()
Authorization: Basic admin:
