###
GET {{$dotenv credstore_url}}/password?name={{$dotenv credstore_keyname}}
Authorization: Basic {{$dotenv credstore_username}}:{{$dotenv credstore_password}}
sapcp-credstore-namespace: {{$dotenv credstore_namespace}}
