### Get Access Token using Client Credentials Flow
# @name requestAccessToken
POST {{$dotenv datasphere_token_endpoint}}
Authorization: Basic {{$dotenv datasphere_clientid}}:{{$dotenv datasphere_clientsecret}}
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
#&response_type=token

### Fill Variables from Response
#@access_token = {{requestAccessToken.response.body.$.access_token}}

### Get Access Token for Cloud Foundry using Password Grant
# @name requestAccessTokenHANA
POST {{$dotenv tokenendpoint}}/oauth/token
Accept: application/json;charset=utf8
Authorization: Basic {{$dotenv clientid}}:{{$dotenv clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}
&client_id={{$dotenv clientid}}
&response_type=token
&login_hint={"origin":"sap.custom"}
### Fill Variables from Response
@user_access_token = {{requestAccessTokenHANA.response.body.$.access_token}}

### Get Access Token for Destination Service
# @name requestDestinationAccessToken
POST {{$dotenv dest_tokenendpoint}}/oauth/token
Authorization: Basic {{$dotenv dest_clientid}}:{{$dotenv dest_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token

### Fill Variables from Response
@destination_access_token = {{requestDestinationAccessToken.response.body.$.access_token}}

### Get Access token from Destination Service using the OAuth2SAMLBearerAssertion Destination
# According to https://api.sap.com/api/SAP_CP_CF_Connectivity_Destination/path/get_destinations__name_
### Read details of one destination
# @name requestProviderDestination
GET {{$dotenv dest_uri}}/destination-configuration/v1/destinations/datasphere
X-user-token: {{user_access_token}}
Authorization: Bearer {{destination_access_token}}
### Fill Variables from Response
@access_token = {{requestProviderDestination.response.body.$.authTokens[0].value}}
### Use Beeceptor to get the SAML Assertion
GET {{$dotenv dest_uri}}/destination-configuration/v1/destinations/datasphere-beeceptor
X-user-token: {{user_access_token}}
Authorization: Bearer {{destination_access_token}}

### Get Access Token from Datasphere
# @name requestAccessTokenDatasphere
POST {{$dotenv datasphere_token_endpoint}}/alias/csw-partner.aws-live-eu10
Authorization: Basic {{$dotenv datasphere_saml_clientid}}:{{$dotenv datasphere_saml_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:saml2-bearer
&assertion={{$dotenv datasphere_saml_assertion}}
&client_id={{$dotenv datasphere_saml_clientid}}
###
# Results in:
# "Error decoding incoming SAML message"
# as the Recipient="https://cswtest.free.beeceptor.com/oauth/token/alias/csw-partner.aws-live-eu10"
# instead of the correct Datasphere Authentication URL
### 
#@access_token = {{requestAccessTokenDatasphere.response.body.$.access_token}}
###
# https://api.sap.com/api/DataImport_API/overview
# @name requestModels
GET {{$dotenv datasphere_endpoint}}/api/v1/dataimport/models
Authorization: Bearer {{access_token}}
###
# https://api.sap.com/api/DatasphereCatalog/overview
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/
Authorization: Bearer {{access_token}}
# Setting this header:
# x-sap-sac-custom-auth: true
# results in Internal Server Error
###
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/$metadata
Authorization: Bearer {{access_token}}
### 
# @name spacesUser
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/spaces
    ?$expand=assets
Authorization: Bearer {{access_token}}
###
@spaceUser={{spacesUser.response.body.value[0].name}}
###
# @name assetsUser
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/assets
    ?$filter=spaceName eq '{{spaceUser}}'
Authorization: Bearer {{access_token}}
###
@assetRelationalDataUrlUser = {{assetsUser.response.body.$.value[0].assetRelationalDataUrl}}
###
# @name assetRelationalData
GET {{assetRelationalDataUrlUser}}
Authorization: Bearer {{access_token}}
###
@entityUser = {{assetRelationalData.response.body.$.value[0].url}}
###
GET {{assetRelationalDataUrlUser}}{{entityUser}}
    ?$top=10
Authorization: Bearer {{access_token}}
###
GET {{assetRelationalDataUrlUser}}{{entityUser}}
    ?$apply=groupby((TransactionCurrency,SalesOrderType,YEAR),aggregate(TotalNetAmount with sum as TotalNetAmountTotal))
    &$filter=TransactionCurrency eq 'EUR'
    &$orderby=YEAR
Authorization: Bearer {{access_token}}
###
GET {{$dotenv datasphere_endpoint}}/dwaas-core/api/v1/discovery
Authorization: Bearer {{access_token}}

### Get Access Token using Authorization Code Flow
GET {{$dotenv datasphere_authorization_url}}
    ?response_type=code
    &client_id={{$dotenv datasphere_clientid}}
    &redirect_uri={{$dotenv datasphere_redirect_uri}}
# https://e719db6c-1717-4264-bef3-b78753ac4f79.authentication.eu10.hana.ondemand.com/oauth/authorize?response_type=code&client_id=sb-0b6e07d5-ec37-4903-9cd3-591c405a2bc4!b254070|client!b3650&redirect_uri=https%3A%2F%2Fcswtest.free.beeceptor.com
### 
# @name requestAccessTokenAuthCodeFlow
POST {{$dotenv datasphere_token_endpoint}}
Authorization: Basic {{$dotenv datasphere_clientid}}:{{$dotenv datasphere_clientsecret}}
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&code={{$dotenv datasphere_code}}
&redirect_uri={{$dotenv datasphere_redirect_uri}}

### Fill Variables from Response
@access_token_code_flow = {{requestAccessTokenAuthCodeFlow.response.body.$.access_token}}

### Use token from Authorization Code Flow
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/
Authorization: Bearer {{access_token_code_flow}}
###
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/$metadata
Authorization: Bearer {{access_token_code_flow}}

### With Token from @sap/datasphere-cli
### See https://blogs.sap.com/2022/09/21/sap-dwc-cli-getting-rid-of-passcodes-thanks-to-oauth-client-support/
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/$metadata
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
# @name spaces
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/spaces
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
@space = {{spaces.response.body.$.value[0].name}}
###
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/spaces('{{space}}')/assets
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
# @name assets
GET {{$dotenv datasphere_endpoint}}/api/v1/dwc/catalog/assets
    ?$filter=spaceName eq '{{space}}'
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
@assetRelationalDataUrl = {{assets.response.body.$.value[0].assetRelationalDataUrl}}
###
# @name assetRelationalData
GET {{assetRelationalDataUrl}}
Authorization: Bearer {{$dotenv datasphere_access_token}}
###
@entity = {{assetRelationalData.response.body.$.value[0].url}}
###
GET {{assetRelationalDataUrl}}{{entity}}
Authorization: Bearer {{$dotenv datasphere_access_token}}
