# Documentation:
# https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/7e306250e08340f89d6c103e28840f30.html
### Get Access Token (Cloud Foundry using Client Credentials)
# @name requestAccessToken
POST {{$dotenv url}}/oauth/token
Authorization: Basic {{$dotenv dest_clientid}}:{{$dotenv dest_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token

### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}

### Read subaccountDestinations
# @name subaccountDestinations
GET {{$dotenv dest_uri}}/destination-configuration/v1/subaccountDestinations/SAP_ABAP_BACKEND
Authorization: Bearer {{access_token}}

### Fill Variables from Response
@backend_url={{subaccountDestinations.response.body.$.URL}}

# @name requestConnectivityAccessToken
POST {{$dotenv url}}/oauth/token
Authorization: Basic {{$dotenv conn_clientid}}:{{$dotenv conn_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token

### Fill Variables from Response
@connectivity_access_token = {{requestConnectivityAccessToken.response.body.$.access_token}}

### Get Access Token (HANA) or Cloud Foundry using Password Grant
# https://blogs.sap.com/2020/03/02/using-postman-for-api-testing-with-xsuaa/
# @name requestUserAccessToken
POST {{$dotenv url}}/oauth/token
Accept: application/json;charset=utf8
Authorization: Basic {{$dotenv client_id}}:{{$dotenv client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}
&client_id={{$dotenv client_id}}
&response_type=token
#&scope=HTML5UserAPIforCF!t55630.Display

### Fill Variables from Response
@user_access_token = {{requestUserAccessToken.response.body.$.access_token}}

###
GET {{backend_url}}/sap/public/ping
Proxy-Authorization: Bearer {{connectivity_access_token}}
SAP-Connectivity-Authentication: Bearer {{user_access_token}}
SAP-Connectivity-SCC-Location_ID: {{$dotenv location_id}}

###
GET {{backend_url}}/sap/bc/ping
Proxy-Authorization: Bearer {{connectivity_access_token}}
SAP-Connectivity-Authentication: Bearer {{user_access_token}}
SAP-Connectivity-SCC-Location_ID: {{$dotenv location_id}}