###
GET http://localhost:4004/document-management
Accept: application/json
###
GET http://localhost:4004/document-management/getRepositoryInfo()
Accept: application/json
###
GET http://localhost:4004/document-management/getFolderTree()
Accept: application/json
###
@folder=folder01
###
GET http://localhost:4004/document-management/getChildren(folderName='{{folder}}')
Accept: application/json

###
POST http://localhost:4004/document-management/createFolder
Accept: application/json
Content-Type: application/json

{
  "folderName": "{{folder}}"
}
