### Get Access Token using Client Credentials Flow
# @name requestAccessToken
POST {{$dotenv epd_collaboration_tokenendpoint}}/oauth/token
Authorization: Basic {{$dotenv epd_collaboration_clientid}}:{{$dotenv epd_collaboration_clientsecret}}
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
#&response_type=token

### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
### Read Collaborations for where the Group TECHNICAL-USER is assigned
GET {{$dotenv epd_collaboration_url}}/odata/v4/CollaborationService_v1/Collaboration
Authorization: Bearer {{access_token}}
### Read Collaborations fora specific Processor (E-Mail)
# @name collaborations
GET {{$dotenv epd_collaboration_url}}/odata/v4/CollaborationService_v1/Collaboration
from: {{$dotenv epd_collaboration_processor}}
Authorization: Bearer {{access_token}}
### Create a new Collaboration
POST {{$dotenv epd_collaboration_url}}/odata/v4/CollaborationService_v1/Collaboration
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Test - Created by REST Client",
  "description": "Created via API",
  "status": "Created",
  "collaborationType": "Y001"
}
###
@docCenterRepositoryId = {{collaborations.response.body.$.value[0].$.docCenterRepositoryId}}
###
GET {{$dotenv epd_collaboration_url}}/cmis
Authorization: Bearer {{access_token}}
###
GET {{$dotenv epd_collaboration_url}}/cmis/{{docCenterRepositoryId}}/root
Authorization: Bearer {{access_token}}
###
GET {{$dotenv epd_collaboration_url}}/odata/v4/WorkflowService_v1/UserTasks
  ?processor={{$dotenv epd_collaboration_processor}}
Authorization: Bearer {{access_token}}
###
GET {{$dotenv epd_collaboration_url}}/odata/v4/BusinessObjectService_v1/CustomBusinessObjects
Authorization: Bearer {{access_token}}
###
GET {{$dotenv epd_collaboration_url}}/odata/v4/CollaborationService_v1/Comments
  ?context=
  &entityId=
  &entityType=
Authorization: Bearer {{access_token}}
