### Get Access Token (Cloud Foundry using Client Credentials)
# @name requestAccessToken
POST {{$dotenv integration_api_tokenendpoint}}
Authorization: Basic {{$dotenv integration_api_clientid}}:{{$dotenv integration_api_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token
### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
###
GET {{$dotenv integration_api_url}}/api/v1/
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{$dotenv integration_api_url}}/api/v1/CustomTagConfigurations('CustomTags')
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{$dotenv integration_api_url}}/api/v1/ServiceEndpoints
  ?$expand=EntryPoints
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{$dotenv integration_api_url}}/api/v1/ArtifactReferences
  ?$top=10
  &$inlinecount=allpages
Authorization: Bearer {{access_token}}
Accept: application/json
###
# @name getIntegrationPackages
GET {{$dotenv integration_api_url}}/api/v1/IntegrationPackages
# Not Implemented
#  ?$expand=CustomTags
Authorization: Bearer {{access_token}}
Accept: application/json
###
@artifacts={{getIntegrationPackages.response.body.d.results[0].IntegrationDesigntimeArtifacts.__deferred.uri}}
###
# @name getArtifacts
GET {{artifacts}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
@Id={{getArtifacts.response.body.d.results[0].Id}}
@Version={{getArtifacts.response.body.d.results[0].Version}}
@Resources={{getArtifacts.response.body.d.results[0].Resources.__deferred.uri}}
@Configurations={{getArtifacts.response.body.d.results[0].Configurations.__deferred.uri}}
@designGuidelineExecutionResults={{getArtifacts.response.body.d.results[0].DesignGuidelineExecutionResults.__deferred.uri}}
###
# @name getResources
GET {{Resources}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
# @name getConfigurations
GET {{Configurations}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
# @name getDesignGuidelineExecutionResults
GET {{designGuidelineExecutionResults}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
@designGuidelineExecutionResultReport={{getDesignGuidelineExecutionResults.response.body.d.results[0].__metadata.media_src}}
###
GET {{designGuidelineExecutionResultReport}}
Authorization: Bearer {{access_token}}
### Execute Design Guideline
POST {{$dotenv integration_api_url}}/api/v1/ExecuteIntegrationDesigntimeArtifactsGuidelines
  ?Id='{{Id}}'
  &Version='{{Version}}'
Authorization: Bearer {{access_token}}
Accept: application/json

### Read Logs
# @name getMessageProcessingLogs
GET {{$dotenv integration_api_url}}/api/v1/MessageProcessingLogs
  ?$top=20
  &$inlinecount=allpages
  &$orderby=LogStart desc
  &$filter=LogStart gt datetime'2025-01-01T00:00' and LogStart lt datetime'2025-01-31T00:00'
  # and Status eq 'FAILED' 
  # and IntegrationFlowName eq 'Employee_Master_Data_from_SAP_SFSF_EC_to_SAP_S4'
  # and IntegrationFlowName eq 'Advance_Shipping_Notification'
  # and IntegrationFlowName eq 'Replicate_Business_Partner_Relationships_from_SAP_S4HANA_Cloud_to_SAP_Field_Service_Management'
Authorization: Bearer {{access_token}}
Accept: application/json
###
@AttachmentsUri={{getMessageProcessingLogs.response.body.d.results[0].Attachments.__deferred.uri}}
@MessageStoreEntriesUri={{getMessageProcessingLogs.response.body.d.results[0].MessageStoreEntries.__deferred.uri}}
@ErrorInformationUri={{getMessageProcessingLogs.response.body.d.results[0].ErrorInformation.__deferred.uri}}
@AdapterAttributesUri={{getMessageProcessingLogs.response.body.d.results[0].AdapterAttributes.__deferred.uri}}
### Read Attachments
# @name getAttachments
GET {{AttachmentsUri}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
@attachment1={{getAttachments.response.body.d.results[0].__metadata.media_src}}
@attachment2={{getAttachments.response.body.d.results[1].__metadata.media_src}}
@attachment3={{getAttachments.response.body.d.results[2].__metadata.media_src}}
@attachment4={{getAttachments.response.body.d.results[3].__metadata.media_src}}
@attachment5={{getAttachments.response.body.d.results[4].__metadata.media_src}}
###
GET {{attachment1}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{attachment2}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{attachment3}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{attachment4}}
Authorization: Bearer {{access_token}}
Accept: application/json
###
GET {{attachment5}}
Authorization: Bearer {{access_token}}
Accept: application/json
### Read Message Store Entries
GET {{MessageStoreEntriesUri}}
Authorization: Bearer {{access_token}}
Accept: application/json
### Read Error Information
GET {{ErrorInformationUri}}
Authorization: Bearer {{access_token}}
Accept: application/json
### Read Adapter Attributes
GET {{AdapterAttributesUri}}
Authorization: Bearer {{access_token}}
Accept: application/json