### Request Access Token
# @name requestAccessToken
POST {{$dotenv jobschedulerurl}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv jobschedulerclientid}}
&client_secret={{$dotenv jobschedulerclientsecret}}
&grant_type=client_credentials
&response_type=token

### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
###
GET {{$dotenv schedulerUrl}}
### Read Jobs
# @name readJobs
GET http://localhost:4004/admin/readJobs()
Authorization: Basic admin:

### Fill Variables from Response
@jobId = {{readJobs.response.body.value[0].jobId}}

### Read Job
# @name readJobs
GET http://localhost:4004/admin/readJobDetails(jobId={{jobId}})
Authorization: Basic admin:

### Read Job Action Logs
# @name readJobActionLogs
GET http://localhost:4004/admin/readJobActionLogs(jobId={{jobId}})
Authorization: Basic admin:

### Read Job Schedules
# @name readSchedules
GET http://localhost:4004/admin/readJobSchedules(jobId={{jobId}})
Authorization: Basic admin:

### Fill Variables from Response
@scheduleId = {{readSchedules.response.body.value[0].scheduleId}}


### Read Job Run Logs
# @name readJobRunLogs
GET http://localhost:4004/admin/readJobRunLogs(jobId={{jobId}},scheduleId='{{scheduleId}}',page_size=200,offset=0)
Authorization: Basic admin:

### Create Job
# @name createJob
POST http://localhost:4004/admin/createJob
Authorization: Basic admin:
Content-Type: application/json

{
  "url": "{{$dotenv url}}/v2/admin/Orders_checkConsistencyInline?ID=guid'64e718c9-ff99-47f1-8ca3-950c850777d4'&IsActiveEntity=true",
  "cron": "* * * * * */5 0"
}

### Fill Variables from Response
#@jobId = {{createJob.response.body.value}}
@active=true
### Update Job
POST http://localhost:4004/admin/updateJob
Authorization: Basic admin:
Content-Type: application/json

{
  "jobId": {{jobId}},
  "active": {{active}}
}

### Delete Job
POST http://localhost:4004/admin/deleteJob
Authorization: Basic admin:
Content-Type: application/json

{
  "jobId": {{jobId}}
}
