### Get Access Token for Cloud Foundry using Password Grant
# https://blogs.sap.com/2020/03/02/using-postman-for-api-testing-with-xsuaa/
# @name requestAccessTokenHANA
POST {{$dotenv cf_login}}/oauth/token
Accept: application/json;charset=utf8
Authorization: Basic cf:
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}

### Fill Variables from Response
@access_token = {{requestAccessTokenHANA.response.body.$.access_token}}

### Based on the blog post from Florian Pfeffer
### Start your SAP HANA Cloud Trial instance with an iOS shortcut
### https://blogs.sap.com/2021/05/08/start-your-sap-hana-cloud-trial-instance-with-an-ios-shortcut/
###
GET {{$dotenv cf_api}}/v3/service_instances
Authorization: Bearer {{access_token}}

###
@hana=fed4bc0d-71b1-479d-857b-14ba1ec98fb0

###
GET {{$dotenv cf_api}}/v3/service_instances/{{hana}}
Authorization: Bearer {{access_token}}

###
GET {{$dotenv cf_api}}/v3/service_instances/{{hana}}/parameters
Authorization: Bearer {{access_token}}

###
GET {{$dotenv cf_api}}/v3/service_instances/{{hana}}/shared_spaces
Authorization: Bearer {{access_token}}

###
PATCH {{$dotenv cf_api}}/v3/service_instances/{{hana}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "parameters": {
        "data": {
            "serviceStopped": false
        }
    }
}