###
GET https://73555000100200018064.npmsrv.cdn.repositories.cloud.sap/
Authorization: Basic {{$dotenv SAP_NPM_AUTH}}
###
GET https://73555000100200018064.npmsrv.cdn.repositories.cloud.sap/-/all
Authorization: Basic {{$dotenv SAP_NPM_AUTH}}
###
GET https://73555000100200018064.npmsrv.cdn.repositories.cloud.sap/@sap/fesr-to-otel-js/-/fesr-to-otel-js-1.3.1.tgz
Authorization: Basic {{$dotenv SAP_NPM_AUTH}}
