### 
GET {{$dotenv ias_scim_endpoint}}/scim/Schemas
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read Users
GET {{$dotenv ias_scim_endpoint}}/scim/Users
# Entra ID Provisioning connection test
#  ?filter=userName+eq+%22AzureAD_Test-340bd08e-3b52-41f3-bd3a-d3de24759387%22
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read Users with Filter
GET {{$dotenv ias_scim_endpoint}}/scim/Users
#  ?filter=urn:sap:cloud:scim:schemas:extension:custom:2.0:Supplier:supplierId eq "13453"
  ?filter=userType eq "partner"
#  ?filter=addresses.country eq "AT"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read User
GET {{$dotenv ias_scim_endpoint}}/scim/Users/{{$dotenv ias_scim_user_guid}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Create User
# @name createUser
POST {{$dotenv ias_scim_endpoint}}/scim/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

< ./default-env-create-minimal.json
###
@userId={{createUser.response.body.id}}
### Update User
PUT {{$dotenv ias_scim_endpoint}}/scim/Users/{{$dotenv ias_scim_user_guid}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

< ./default-env-update.json
###
DELETE {{$dotenv ias_scim_endpoint}}/scim/Users/{{userId}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
POST {{$dotenv ias_scim_endpoint}}/scim/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:sap:2.0:User",
    "urn:sap:cloud:scim:schemas:extension:custom:2.0:Customer"
  ],
  "userName": "johny.smith",
  "name": {
    "familyName": "Smith",
    "givenName": "Johny"
  },
  "userType": "Partner",
  "active": true,
  "emails": [
    {
      "type": "work",
      "value": "{{$dotenv scim_user_email}}",
      "primary": true
    }
  ],
  "urn:ietf:params:scim:schemas:extension:sap:2.0:User": {
    "status": "active",
    "applicationId": "9f3599c7-ff65-42df-a63b-c9dc04930da2",
    "sendMail": true,
    "targetUrl": "https://csw-dev-azure.launchpad.cfapps.eu20.hana.ondemand.com/site/csw",
    "emails": [
      {
        "type": "work",
        "value": "{{$dotenv scim_user_email}}",
        "primary": true
      }
    ]
  },
  "urn:sap:cloud:scim:schemas:extension:custom:2.0:Customer": {
    "customerId": "17100001"
  }
}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Users
  ?filter=emails.value eq "{{$dotenv ias_scim_user_email}}"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Filter by Group Display Name with equals
GET {{$dotenv ias_scim_endpoint}}/scim/Users
  ?filter=groups.display eq "SAP_BTP_Admin"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Filter by Group Display Name with contains
GET {{$dotenv ias_scim_endpoint}}/scim/Users
  ?filter=groups.display co "SAP_BTP"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Groups
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Groups
  ?filter=displayName co "SAP_BTP_"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Groups
  ?filter=urn:ietf:params:scim:schemas:extension:sap:2.0:Group:applicationId eq "{{$dotenv ias_applicationIdentifier}}"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/Applications/v1/
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/scim/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Not Provided by IAS
GET {{$dotenv ias_scim_endpoint}}/service/scim/Schemas
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/scim/Users/{{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
PUT {{$dotenv ias_scim_endpoint}}/service/scim/Users/{{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

< ./default-env-service.json
### Works with the client ID and a secret created according to:
# https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/9ea13fe831e24620bc89affab178ff93.html
GET {{$dotenv ias_scim_endpoint}}/service/users
  ?name_id={{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/users/3DA51F61-37CF-49EC-BFC3-4E8531A4BD88
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/users?email={{$dotenv ias_email}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Invite User to IAS
POST {{$dotenv ias_scim_endpoint}}/cps/invite/
Content-Type: application/json
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}

{
  "inviteeEmail": "{{$dotenv ias_email}}",
  "inviteeFirstName": "John",
  "inviteeLastName": "Doe",
  "inviterName": "John Doe",
  "footerText": "Invitation footer sample text",
  "headerText": "Invitation header sample text",
  "targetUrl": "http://www.myserviceprovider.com/protected_home_page/",
  "sourceUrl": "http://www.myserviceprovider.com/public_home_page/"
}
