### 
GET {{$dotenv ias_scim_endpoint}}/scim/Schemas
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read Users
GET {{$dotenv ias_scim_endpoint}}/scim/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read User
GET {{$dotenv ias_scim_endpoint}}/scim/Users/{{$dotenv ias_scim_user_guid}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Read User
PUT {{$dotenv ias_scim_endpoint}}/scim/Users/{{$dotenv ias_scim_user_guid}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

< ./default-env.json

### Filter by Group Display Name with equals
GET {{$dotenv ias_scim_endpoint}}/scim/Users
  ?filter=groups.display eq "SAP_BTP_Admin"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Filter by Group Display Name with contains
GET {{$dotenv ias_scim_endpoint}}/scim/Users
  ?filter=groups.display co "SAP_BTP"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Groups
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/scim/Groups
  ?filter=displayName co "SAP_BTP_"
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/Applications/v1/
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/scim/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Not Provided by IAS
GET {{$dotenv ias_scim_endpoint}}/service/scim/Schemas
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/scim/Users/{{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
PUT {{$dotenv ias_scim_endpoint}}/service/scim/Users/{{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
Content-Type: application/scim+json

< ./default-env-service.json
### Works with the client ID and a secret created according to:
# https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/9ea13fe831e24620bc89affab178ff93.html
GET {{$dotenv ias_scim_endpoint}}/service/users
  ?name_id={{$dotenv ias_scim_user_to_search}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/users/3DA51F61-37CF-49EC-BFC3-4E8531A4BD88
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### 
GET {{$dotenv ias_scim_endpoint}}/service/users?email={{$dotenv ias_email}}
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
### Invite User to IAS
POST {{$dotenv ias_scim_endpoint}}/cps/invite/
Content-Type: application/json
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}

{
  "inviteeEmail": "{{$dotenv ias_email}}",
  "inviteeFirstName": "John",
  "inviteeLastName": "Doe",
  "inviterName": "John Doe",
  "footerText": "Invitation footer sample text",
  "headerText": "Invitation header sample text",
  "targetUrl": "http://www.myserviceprovider.com/protected_home_page/",
  "sourceUrl": "http://www.myserviceprovider.com/public_home_page/"
}
