### IPS SCIM Proxy
# https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/proxy-sap-build-work-zone-standard-edition?locale=en-US
###
GET {{$dotenv ias_scim_endpoint}}/ipsproxy/service/api/v1/scim/{{$dotenv ias_scim_proxy_id}}/Users
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
###
GET {{$dotenv ias_scim_endpoint}}/ipsproxy/service/api/v1/scim/{{$dotenv ias_scim_proxy_id}}/Groups
Authorization: Basic {{$dotenv ias_scim_username}}:{{$dotenv ias_scim_password}}
