# @name requestAccessToken
POST {{$dotenv xsuaa_apiaccess_tokenendpoint}}/oauth/token
Authorization: Basic {{$dotenv xsuaa_apiaccess_clientid}}:{{$dotenv xsuaa_apiaccess_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token

### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}

### 
# @name readUsers
GET {{$dotenv xsuaa_apiaccess_apiurl}}/Users
Authorization: Bearer {{access_token}}
###
GET {{$dotenv xsuaa_apiaccess_apiurl}}/Users
  ?sortBy=userName
Authorization: Bearer {{access_token}}
### 
# @name readGroups
GET {{$dotenv xsuaa_apiaccess_apiurl}}/Groups
Authorization: Bearer {{access_token}}

### 
# @name readGroupBookshopAdmin
GET {{$dotenv xsuaa_apiaccess_apiurl}}/Groups/BookshopAdmin
Authorization: Bearer {{access_token}}

### 
# @name readRoletemplaes
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/apps/roletemplates
Authorization: Bearer {{access_token}}

### 
# @name readRoleCollection
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/rolecollections/?showGroups=true&showRoles=true&showUsers=true
Authorization: Bearer {{access_token}}

### 
# @name readApps
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/apps/
Authorization: Bearer {{access_token}}

### 
# @name readApp
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/apps/bookshop-demo!t73843
Authorization: Bearer {{access_token}}

### 
# @name readUsersCAP
GET http://localhost:4004/odata/v4/admin/readUsers()
Authorization: Basic admin:

### 
# @name readUsersSDK
GET http://localhost:4004/odata/v4/admin/readUsersSDK()
Authorization: Basic admin:

### https://api.sap.com/api/TrustConfigurationAPI/overview
### Get the Origin Key
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/identity-providers
Authorization: Bearer {{access_token}}
### Read Role Collection Attribute Mappings
# @name readRoleCollectionAttributeMappings
GET {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/identity-providers/{{$dotenv xsuaa_apiaccess_originKey}}/attributes/rolecollections
Authorization: Bearer {{access_token}}
### Delete Role Collection Attribute Mapping
DELETE {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/identity-providers/{{$dotenv xsuaa_apiaccess_originKey}}/attributes/{{$dotenv attributeName}}/{{$dotenv comparisonOperator}}/{{$dotenv attributeValue}}/rolecollections/{{$dotenv roleCollectionName}}
Authorization: Bearer {{access_token}}
### Create Role Collection Attribute Mapping
POST {{$dotenv xsuaa_apiaccess_apiurl}}/sap/rest/authorization/v2/identity-providers/{{$dotenv xsuaa_apiaccess_originKey}}/attributes
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
   "attributeName": "{{$dotenv attributeName}}",
   "attributeValue": "{{$dotenv attributeValue}}",
   "operator": "{{$dotenv comparisonOperator}}",
   "roleCollectionName": "{{$dotenv roleCollectionName}}"
}
