# @name requestAccessTokenClientCredentials
POST {{$dotenv ias_base_url}}/oauth2/token
Authorization: Basic {{$dotenv ias_client_id}}:{{$dotenv ias_client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token
### Fill Variables from Response
#@access_token = {{requestAccessTokenClientCredentials.response.body.$.access_token}}

### Get Token from SAP Identity Authentication Service (IAS)
# @name requestAccessToken
POST {{$dotenv ias_base_url}}/oauth2/token
Authorization: Basic {{$dotenv ias_client_id}}:{{$dotenv ias_client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv ias_username}}
&password={{$dotenv ias_password}}
&response_type=token
### Fill Variables from Response
@ias_id_token = {{requestAccessToken.response.body.$.id_token}}
@ias_access_token = {{requestAccessToken.response.body.$.access_token}}
###
# IAS Token Exchange using the Consuming APIs from Other Applications configuration:
# https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/consume-apis-from-other-applications
# @name requestSAMLBearerToken
POST {{$dotenv ias_base_url}}/oauth2/token
Authorization: Basic {{$dotenv ias_client_id}}:{{$dotenv ias_client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:token-exchange
&client_id={{$dotenv ias_client_id}}
&subject_token={{ias_id_token}}
&subject_token_type=urn:ietf:params:oauth:token-type:id_token
&resource=urn:sap:identity:application:provider:name:{{$dotenv ias_dependency_name}}
#&subject_token={{ias_access_token}}
#&subject_token_type=urn:ietf:params:oauth:token-type:access_token
&scope=openid email
&requested_token_type=urn:ietf:params:oauth:token-type:saml2
### Get Token from S/4HANA Cloud
# @name requestAccessTokenS4
POST {{$dotenv s4hanahost}}/sap/bc/sec/oauth2/token
Authorization: Basic {{$dotenv s4_client_id}}:{{$dotenv s4_client_secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer
&assertion={{ias_id_token}}
### Write response into local variables
@access_token={{requestAccessTokenS4.response.body.$.access_token}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/$metadata
Authorization: Bearer {{access_token}}