# https://api.sap.com/api/API_PURCHASING_SOURCE_SRV/overview
# Communication Scenario SAP_COM_0162
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PURCHASING_SOURCE_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PURCHASING_SOURCE_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PURCHASING_SOURCE_SRV/A_PurchasingSource
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json