### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/A_SalesOrderSimulation
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createSalesOrder
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/A_SalesOrderSimulation
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "SalesOrderType": "OR",
  "SalesOrganization": "1010",
  "DistributionChannel": "10",
  "OrganizationDivision": "00",
  "SoldToParty": "10100003",
  "PurchaseOrderByCustomer": "PO-GROUP-88",
  "SalesOrderDate": "\/Date(1720051200000)\/",
  "PricingDate": "\/Date(1720051200000)\/",
  "RequestedDeliveryDate": "\/Date(1720051200000)\/",
  "ShippingCondition": "01",
  "CompleteDeliveryIsDefined": true,
  "to_Item": [
    {
      "SalesOrder": "10",
      "SalesOrderItem": "10",
      "Material": "TG11",
      "RequestedQuantity": "100",
      "RequestedQuantityUnit": "PC",
      "to_PricingElement": [],
      "to_ScheduleLine": [
        {
          "SalesOrder": "10",
          "SalesOrderItem": "10",
          "ScheduleLine": "1",
          "RequestedDeliveryDate": "\/Date(1720051200000)\/",
          "ConfirmedDeliveryDate": null,
          "OrderQuantityUnit": "PC",
          "ScheduleLineOrderQuantity": "100"
        }
      ]
    }
  ]
}