### Cloud: https://api.sap.com/api/API_BUSINESS_PARTNER/overview
### Communication Scenario: Business Partner, Customer and Supplier Integration (SAP_COM_0008)
### OnPrem: https://api.sap.com/api/OP_API_BUSINESS_PARTNER_SRV/overview
### api.sap.com Sandbox
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/$metadata
APIKey: {{$dotenv apikey}}
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
  ?$top=10
  &$filter=CreationDate gt datetime'2020-09-08T00:00' and BusinessPartnerCategory eq '1' and Customer ne ''
  &$expand=to_AddressIndependentEmail,to_BusinessPartnerAddress,to_BusinessPartnerAddress/to_EmailAddress
  &$inlinecount=allpages
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BPIntlAddressVersion/$count
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}{{$dotenv test_path}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner/$count
  ?$filter=Customer ne ''
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
  ?$top=10
  &$skip=0
  &$inlinecount=allpages
  &$expand=to_BusinessPartnerAddress,to_BusinessPartnerAddress/to_AddressUsage,to_Customer,to_Customer/to_CustomerSalesArea
  &$filter=Customer ne ''
  # and LastChangeDate gt '2024-01-01T00:00'
  #&$select=Customer,BusinessPartnerFullName
  &$orderby=Customer
  #,to_BusinessPartnerAddress/StreetName
  #
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesArea
  ?$inlinecount=allpages
  &$top=10
  &$filter=SalesOrganization eq '1010' and DistributionChannel eq '10'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
# @name getBusinessPartner
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
  ?$filter=BusinessPartner eq '{{$dotenv BusinessPartner}}'
  &$inlinecount=allpages
  &$expand=to_BusinessPartnerTax,to_BusinessPartnerAddress,to_BusinessPartnerAddress/to_AddressUsage,to_BusinessPartnerAlias,to_BusinessPartnerRole,to_Customer,to_Customer/to_CustomerSalesArea,to_Customer/to_CustomerSalesArea/to_PartnerFunction,to_Customer/to_CustomerSalesArea/to_SalesAreaTax,to_Customer/to_CustAddrDepdntExtIdentifier,to_Customer/to_CustomerCompany,to_Customer/to_CustomerCompany/to_CompanyText,to_Customer/to_CustomerText
  #,to_Customer/to_CustomerSalesArea/to_SalesAreaText
  &top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
@toSalesAreaTextUri={{getBusinessPartner.response.body.d.results[0].to_Customer.to_CustomerSalesArea.results[0].to_SalesAreaText.__deferred.uri}}
###
# @name getSalesAreaText
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesAreaText
  ?$inlinecount=allpages
  &$filter=Customer eq '{{$dotenv BusinessPartner}}'
  &top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
@toSpecificSalesAreaTextUri={{getSalesAreaText.response.body.d.results[0].__metadata.uri}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
### Create A_CustomerSalesAreaText
POST {{toSalesAreaTextUri}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "Language": "DE",
  "LongTextID": "TX01",
  "LongText": "Test from REST Client
With a line break"
}
### Update A_CustomerSalesAreaText
PATCH {{toSpecificSalesAreaTextUri}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "LongText": "Update test from REST Client"
}
###
# @name createBusinessPartner
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "BusinessPartnerCategory" : "2",
  "OrganizationBPName1" : "TEST_ORG1",
  "OrganizationBPName2" : "name2",
  "OrganizationBPName3" : "name3",
  "OrganizationBPName4" : "name4",
  "SearchTerm1" : "test",
  "AuthorizationGroup" : "0001",
  "LegalForm" : "01",
  "OrganizationFoundationDate" : "\/Date(253402300799000)\/",
  "OrganizationLiquidationDate" : "\/Date(253402300799000)\/",
  "BusinessPartnerType" : "0001",
  "BusinessPartnerIsBlocked" : false,
  "to_BuPaIndustry" : [
    {
      "IndustrySector" : "01",
      "IndustrySystemType" : "0001",
      "IsStandardIndustry" : "X"

    }
  ],
  "to_BusinessPartnerAddress" : [
    {
      "Country" : "IN",
      "HouseNumber" : "5",
      "StreetName" : "whitefield",
      "PostalCode" : "260097",
      "CityName" : "Bangalore",
      "Language" : "EN",
      "to_AddressUsage" : [
        {
          "AddressUsage" : "XXDEFAULT",
          "ValidityEndDate" : "\/Date(253402300799000+0000)\/"
        }
      ]
    }
  ],
  "to_BusinessPartnerRole" : [
    {
      "BusinessPartnerRole" : "FLCU00",
      "ValidFrom" : "\/Date(1484092800000+0000)\/",
      "ValidTo" : "\/Date(253402300799000+0000)\/"
    },
    {
      "BusinessPartnerRole" : "FLCU01",
      "ValidFrom" : "\/Date(1451606400000+0000)\/",
      "ValidTo" : "\/Date(253402300799000+0000)\/"
    }
  ],
  "to_Customer" : {
    "PostingIsBlocked" : false,
    "to_CustomerSalesArea" : [
      {
        "SalesOrganization" : "1010",
        "DistributionChannel" : "10",
        "Division" : "00",
        "SalesDistrict" : "",
        "Currency" : "EUR",
        "CustomerABCClassification" : "23",
        "CustomerAccountAssignmentGroup" : "01",
        "CustomerGroup" : "01",
        "CustomerPaymentTerms" : "0001",
        "CustomerPriceGroup" : "",
        "CustomerPricingProcedure" : "",
        "DeliveryPriority" : "01",
        "ItemOrderProbabilityInPercent" : "50",
        "ShippingCondition" : "01",
        "SupplyingPlant" : "1010",
        "CompleteDeliveryIsDefined" : false,
        "DeliveryIsBlockedForCustomer" : "",
        "OrderCombinationIsAllowed" : false,
        "OrderIsBlockedForCustomer" : "",
        "PartialDeliveryIsAllowed" : "A",
        "to_PartnerFunction" : [
          {
            "PartnerCounter" : "9",
            "PartnerFunction" : "SP",
            "BPCustomerNumber" : "",
            "CustomerPartnerDescription" : "",
            "DefaultPartner" : true
          },
          {
            "PartnerCounter" : "",
            "PartnerFunction" : "BP",
            "BPCustomerNumber" : "",
            "CustomerPartnerDescription" : "",
            "DefaultPartner" : false
          },
          {
            "PartnerCounter" : "",
            "PartnerFunction" : "PY",
            "BPCustomerNumber" : "",
            "CustomerPartnerDescription" : "",
            "DefaultPartner" : false
          },
          {
            "PartnerCounter" : "",
            "PartnerFunction" : "SH",
            "BPCustomerNumber" : "",
            "CustomerPartnerDescription" : "",
            "DefaultPartner" : false
          }
        ]
      }
    ],
    "to_CustomerCompany" : [
      {
        "CompanyCode" : "1010",
        "CustomerSupplierClearingIsUsed" : false,
        "IsToBeLocallyProcessed" : false,
        "ItemIsToBePaidSeparately" : false,
        "PaymentTerms" : "NT30",
        "PaytAdviceIsSentbyEDI" : false,
        "PhysicalInventoryBlockInd" : false,
        "ReconciliationAccount" : "12100000",
        "RecordPaymentHistoryIndicator" : false
      }
    ]
  }
}