### Cloud: https://api.sap.com/api/API_JOURNALENTRYITEMBASIC_SRV/overview
# SAP_COM_0087
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### $metadata
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_CompanyCode
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_CostCenter
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_ProfitCenter
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_GLAccountInChartOfAccounts
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic/$count
  ?$filter=CompanyCode eq '{{$dotenv CompanyCode}}' and LedgerFiscalYear eq '{{$dotenv FiscalYear}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV/A_JournalEntryItemBasic
  ?$top=10000
  &$skip=10000
  &$filter=CompanyCode eq '{{$dotenv CompanyCode}}' and LedgerFiscalYear eq '{{$dotenv FiscalYear}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json