### Cloud: https://api.sap.com/api/API_SALES_ORDER_SRV/overview
### OnPrem: https://api.sap.com/api/OP_API_SALES_ORDER_SRV_0001/overview
### api.sap.com Sandbox
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/$metadata
APIKey: {{$dotenv apikey}}
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
  ?$top=10
  &$filter=CreationDate eq datetime'2016-09-08T00:00'
  &$inlinecount=allpages
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
  ?$top=10
#  &$skip=9
  &$filter=SoldToParty eq '10100003'
  &$orderby=SalesOrder desc
  &$expand=to_Item,to_Item/to_ScheduleLine,to_Item/to_SubsequentProcFlowDocItem,to_BillingPlan,to_SubsequentProcFlowDoc,to_PrecedingProcFlowDoc,to_RelatedObject,to_PaymentPlanItemDetails
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createSalesOrderFromFile
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

#< ./default-env-API_SALES_ORDER_SRV-create.json
#< ./API_SALES_ORDER_SRV-create.json
< ./API_SALES_ORDER_SRV-create-2.json
###
@salesOrderFromFile={{createSalesOrderFromFile.response.body.d.SalesOrder}}
###
# Read the created Sales Order
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder('{{salesOrderFromFile}}')
  ?$expand=to_Item,to_Item/to_ScheduleLine
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json

###
# @name createSalesOrder
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "SalesOrderType": "OR",
  "SalesOrganization": "{{$dotenv SalesOrganization}}",
  "DistributionChannel": "10",
  "OrganizationDivision": "00",
  "SoldToParty": "{{$dotenv SoldToParty}}",
  "PurchaseOrderByCustomer": "{{$dotenv PurchaseOrderByCustomer}}",
  "SalesOrderDate": "\/Date(1738678316000)\/",
  "PricingDate": "\/Date(1738678316000)\/",
  "RequestedDeliveryDate": "\/Date(1738678316000)\/",
  "CompleteDeliveryIsDefined": true,
  "to_Item": [
    {
      "SalesOrderItem": "10",
      "Material": "{{$dotenv Material}}",
      "RequestedQuantity": "21",
      "RequestedQuantityUnit": "PC",
      "to_PricingElement": [],
      "to_ScheduleLine": []
    }
  ]
}

###
@salesOrder={{createSalesOrder.response.body.d.SalesOrder}}
###
# Read the created Sales Order
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder('{{salesOrder}}')
  ?$expand=to_Item,to_Item/to_ScheduleLine
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
