# Cloud: https://api.sap.com/api/API_CLFN_CLASS_SRV/overview
# SAP_COM_0163
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/A_ClfnClassForKeyDate
    ?$inlinecount=allpages
    &$top=10
    &$expand=to_ClassCharacteristic,to_ClassDescription
    &$filter=ClassType eq '001' and ValidityStartDate le datetime'2026-02-12T00:00:00.000' and ValidityEndDate ge datetime'2026-02-12T00:00:00.000'
    #&$filter=ClassInternalID eq '17'
    #&$filter=Class eq '{{$dotenv Class}}'
    &$select=ClassType,Class,to_ClassCharacteristic/Characteristic,to_ClassDescription/Language,to_ClassDescription/ClassDescription
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/A_ClfnClassDescForKeyDate
    ?$inlinecount=allpages
    &$top=10
    &$filter=ClassInternalID eq '{{$dotenv ClassInternalID}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/A_ClfnClassCharcForKeyDate
    ?$inlinecount=allpages
    &$top=10
    #&$filter=ClassInternalID eq '{{$dotenv ClassInternalID}}'
    &$filter=CharcInternalID eq '1796'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/A_ClfnClassKeywordForKeyDate
    ?$inlinecount=allpages
    &$top=10
    &$filter=ClassInternalID eq '{{$dotenv ClassInternalID}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CLFN_CLASS_SRV/A_ClfnClassTextForKeyDate
    ?$inlinecount=allpages
    &$top=10
    &$filter=ClassInternalID eq '{{$dotenv ClassInternalID}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json