# https://api.sap.com/api/API_COSTCENTER_SRV/overview
# SAP_COM_0087
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_COSTCENTER_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_COSTCENTER_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenter
  ?$inlinecount=allpages
  &$top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_COSTCENTER_SRV/A_CostCenterText
  ?$inlinecount=allpages
  &$top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json