# https://api.sap.com/api/API_BILL_OF_MATERIAL_SRV_0002/overview
# SAP_COM_0105
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOM/$count
  ?$filter=BillOfMaterialVariantUsage eq 'A'
  # and ({{$dotenv PlantFilter}})
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOM
  ?$inlinecount=allpages
  &$top=10
  &$expand=to_BillOfMaterialItem,to_BillOfMaterialLongText,to_BillOfMaterialUsage,to_BillOfMaterialUsage/to_BillOfMaterialUsageText
  #&$filter=BillOfMaterialVariantUsage eq 'A' and ({{$dotenv PlantFilter}} or Plant eq '')
  &$filter=BillOfMaterial eq '00049025' and BillOfMaterialCategory eq 'M'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Read MaterialBOMSubItem entities
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOMSubItem
    ?$top=10
    &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json

### Filter MaterialBOM by Plant
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOM
    ?$inlinecount=allpages
    &$filter=Plant eq '1020' or Plant eq '2210'
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Filter MaterialBOMItem by Material
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOMItem
    ?$inlinecount=allpages
    &$filter=BillOfMaterialComponent eq 'RM001'
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOMItemLongText
    ?$inlinecount=allpages
    &$filter=Plant eq '1020' or Plant eq '2210'
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### MaterialBOMLongText
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOMLongText
    ?$inlinecount=allpages
    &$filter=Plant eq '1020' or Plant eq '2210'
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### MaterialBOMSubItem
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MaterialBOMSubItem
    ?$inlinecount=allpages
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### A_BillOfMaterialUsage
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/A_BillOfMaterialUsage
    ?$inlinecount=allpages
    &$top=15
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### A_BillOfMaterialUsage
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/A_BillOfMaterialUsage
    ?$format=xlsx
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### MBOMItmObjDpnAssignment
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_BILL_OF_MATERIAL_SRV;v=0002/MBOMItmObjDpnAssignment
    ?$inlinecount=allpages
    &$top=5
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json