###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem/$count
  ?$filter=CompanyCode eq '1020' or CompanyCode eq '2210'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_GLACCOUNTLINEITEM/GLAccountLineItem
  ?$inlinecount=allpages
  &$top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json