# Cloud: https://api.sap.com/api/API_WORK_CENTERS/overview
# Communication Scenario SAP_COM_0104

### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenters
  ?$top=10
  &$inlinecount=allpages
  &$filter=Plant eq '1020'
  #&$filter=WorkCenterInternalID eq '10000186'
  &$expand=to_WorkCenterAllCapacity,to_WorkCenterAllCapacity/to_Capacity,to_WorkCenterAllCapacity/to_Capacity/to_CapacityInterval,to_WorkCenterAllCapacity/to_Capacity/to_CapacityInterval/to_CapacityShift
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapOrderPerBucket/$count
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapOrderPerBucket
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapPerBucket
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterAllCapacity_2
  ?$top=10
  &$inlinecount=allpages
  &$filter=CapacityInternalID eq '10000186'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapacity
  ?$top=10
  &$inlinecount=allpages
  &$filter=CapacityInternalID eq '10000186'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapacityInterval_2
  ?$top=10
  &$inlinecount=allpages
  &$filter=CapacityInternalID eq '10000186'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_WORK_CENTERS/A_WorkCenterCapacityShift_2
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
