# https://api.sap.com/api/API_ENTERPRISE_PROJECT_SRV_0002/overview
# SAP_COM_0308
# 
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_ENTERPRISE_PROJECT_SRV;v=0002/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_ENTERPRISE_PROJECT_SRV;v=0002/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_ENTERPRISE_PROJECT_SRV;v=0002/A_EnterpriseProject
  ?$inlinecount=allpages
  &$top=1
  &$expand=to_EnterpriseProjectElement,to_EnterpriseProjectJVA,to_EntProjBlkFunc,to_EntProjectPublicSector,to_EntProjRole,to_EntProjTeamMember,to_EnterpriseProjectElement/to_EntProjectElementJVA,to_EnterpriseProjectElement/to_EntProjectElmntPublicSector,to_EnterpriseProjectElement/to_EntProjElmntBlkFunc,to_EnterpriseProjectElement/to_ParentProjElement,to_EnterpriseProjectElement/to_EntProjElmntDlvbrl,to_EnterpriseProjectElement/to_EntProjElmntWorkItem,to_EnterpriseProjectElement/to_SubProjElement
  &$filter=ProjectUUID eq guid'{{$dotenv ProjectUUID}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### A_EntProjElmntWorkItem
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_ENTERPRISE_PROJECT_SRV;v=0002/A_EntProjElmntWorkItem
  ?$inlinecount=allpages
  &$top=10
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json