### Cloud: https://api.sap.com/api/API_PRODUCT_SRV/overview
### Communication Scenario: SAP_COM_0009
### OnPrem: 
### api.sap.com Sandbox
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_PRODUCT_SRV/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_PRODUCT_SRV/$metadata
APIKey: {{$dotenv apikey}}
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product/$count
APIKey: {{$dotenv apikey}}
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product
  ?$top=10
  &$filter=CreationDate gt datetime'2018-09-08T00:00'
  &$inlinecount=allpages
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
# @name readProducts
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product
  ?$top=10
#  &$skip=9
#  &$filter=Product eq '{{$dotenv Product}}'
#  &$filter=ProductType eq 'MAT'
#  &$filter=ProductType eq 'FERT'
#  &$filter=ProductType eq 'KMAT'
  &$expand=to_Description,to_Plant,to_ProductSales,to_ProductBasicText,to_SalesDelivery,to_SalesDelivery/to_SalesText,to_ProductUnitsOfMeasure
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
Accept-Language: en
###
# @name readProductsViaAPIManagement
GET {{$dotenv s4hana_apimgmt_host}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product
	?$top=10
#  &$skip=9
  &$filter=Product eq '{{$dotenv Product}}'
#  &$filter=ProductType eq 'MAT'
#  &$filter=ProductType eq 'FERT'
#  &$filter=ProductType eq 'KMAT'
  &$expand=to_Description,to_Plant,to_ProductSales
  &$inlinecount=allpages
#  &APIKey={{$dotenv s4hana_apikey}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_apimgmt_password}}
APIKey: {{$dotenv s4hana_apikey}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductPlant
  ?$top=10
  &$filter=Plant eq '{{$dotenv plant}}'
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
@product={{readProducts.response.body.d.results[0].Product}}
#@product=TG11
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product('{{product}}')
  ?$expand=to_Description,to_Plant,to_ProductSales
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductSalesDelivery
  ?$top=10
  &$filter=ProductSalesOrg eq '{{$dotenv ProductSalesOrg}}' and ProductDistributionChnl eq '{{$dotenv ProductDistributionChnl}}' and ItemCategoryGroup eq '{{$dotenv ItemCategoryGroup}}'
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductSupplyPlanning
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
# @name readProductDescriptions
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductDescription
  ?$top=10
  &$filter=Product eq '{{$dotenv Product}}' and Language eq 'DE'
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
@productDescription={{readProductDescriptions.response.body.d.results[0].ProductDescription}}
@productDescriptionURI={{readProductDescriptions.response.body.d.results[0].__metadata.uri}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name updateProductDescription
PATCH {{productDescriptionURI}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
	"ProductDescription": "{{$dotenv productDescription}}"
}
###
# @name createProduct
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "Product": "",
  "ProductType": "MAT",
  "BaseUnit": "EA",
  "to_Description": {
    "results": [
      {
        "Product": "",
        "Language": "EN",
        "ProductDescription": "test API"
      }
    ]
  }
}
###
# @name createProductViaAPIManagement
POST {{$dotenv s4hana_apimgmt_host}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_Product
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_apimgmt_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
APIKey: {{$dotenv s4hana_apikey}}
Content-Type: application/json

{
  "Product": "",
  "ProductType": "MAT",
  "BaseUnit": "EA",
  "to_Description": {
    "results": [
      {
        "Product": "",
        "Language": "EN",
        "ProductDescription": "test API"
      }
    ]
  }
}
###
@longTextURL={{createProduct.response.body.$.error.innererror.errordetails[0].longtext_url}}
###
GET {{$dotenv s4hanahost}}{{longTextURL}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
# @name createProductSupplyPlanning
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_PRODUCT_SRV/A_ProductSupplyPlanning
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
	"Product": "BIKE-GRP01-003",
	"Plant": "1010",
	"FixedLotSizeQuantity": "0",
	"MaximumLotSizeQuantity": "20",
	"MinimumLotSizeQuantity": "10",
	"LotSizeRoundingQuantity": "0",
	"LotSizingProcedure": "EX",
	"MRPType": "PD",
	"MRPResponsible": "001",
	"SafetyStockQuantity": "0",
	"MinimumSafetyStockQuantity": "0",
	"PlanningTimeFence": "0",
	"ABCIndicator": "B",
	"MaximumStockQuantity": "0",
	"ReorderThresholdQuantity": "0",
	"PlannedDeliveryDurationInDays": "0",
	"SafetyDuration": "0",
	"PlanningStrategyGroup": "",
	"TotalReplenishmentLeadTime": "0",
	"ProcurementType": "X",
	"ProcurementSubType": "",
	"AssemblyScrapPercent": "0.00",
	"AvailabilityCheckType": "SR",
	"GoodsReceiptDuration": "0",
	"MRPGroup": "0001",
	"DfltStorageLocationExtProcmt": "",
	"ProdRqmtsConsumptionMode": "",
	"BackwardCnsmpnPeriodInWorkDays": "0",
	"FwdConsumptionPeriodInWorkDays": "0",
	"BaseUnit": "EA",
	"PlanAndOrderDayDetermination": "",
	"RoundingProfile": "",
	"LotSizeIndependentCosts": "0.00",
	"MRPPlanningCalendar": "",
	"RangeOfCvrgPrflCode": "",
	"IsSafetyTime": "",
	"PerdPrflForSftyTme": "",
	"IsMRPDependentRqmt": "",
	"InHouseProductionTime": "0",
	"ProductIsForCrossProject": "",
	"StorageCostsPercentageCode": "",
	"SrvcLvl": "0.0",
	"MRPAvailabilityType": "",
	"FollowUpProduct": "",
	"RepetitiveManufacturingIsAllwd": false,
	"DependentRequirementsType": "",
	"IsBulkMaterialComponent": false,
	"RepetitiveManufacturingProfile": "",
	"RqmtQtyRcptTaktTmeInWrkgDays": "0",
	"ForecastRequirementsAreSplit": "",
	"EffectiveOutDate": null,
	"MRPProfile": "",
	"ComponentScrapInPercent": "0.00",
	"ProductIsToBeDiscontinued": "",
	"ProdRqmtsAreConsolidated": "",
	"MatlCompIsMarkedForBackflush": "",
	"ProposedProductSupplyArea": "",
	"Currency": "EUR",
	"PlannedOrderActionControl": ""
}