### Cloud: https://api.sap.com/api/API_SALES_ORDER_SRV/overview
# SAP_COM_0109
### OnPrem: https://api.sap.com/api/OP_API_SALES_ORDER_SRV_0001/overview
### api.sap.com Sandbox
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/$metadata
APIKey: {{$dotenv apikey}}
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
  ?$top=10
  &$filter=CreationDate eq datetime'2016-09-08T00:00'
  &$inlinecount=allpages
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
  ?$top=1
#  &$skip=9
#  &$filter=SoldToParty eq '10100003'
  &$filter=OverallSDProcessStatus ne 'C' and CreationDate ge datetime'2025-01-01T00:00'
  # and OverallSDDocumentRejectionSts eq ''
  &$orderby=SalesOrder desc
  # Results in:
  # Resource not found for the segment 'to_Items'
  # &$select=*,to_Items/*,to_Items/to_ScheduleLine/*,to_Items/to_Partner/*,to_Partner/*
  &$expand=to_Item,to_Item/to_ScheduleLine,to_Item/to_Partner,to_Partner
  #,to_Item/to_SubsequentProcFlowDocItem,to_BillingPlan,to_SubsequentProcFlowDoc,to_PrecedingProcFlowDoc,to_RelatedObject,to_PaymentPlanItemDetails
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrderItem
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createSalesOrderFromFile
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

#< ./default-env-API_SALES_ORDER_SRV-create.json
#< ./API_SALES_ORDER_SRV-create.json
< ./API_SALES_ORDER_SRV-create-2.json
#< ./API_SALES_ORDER_SRV-create-with-payment-plan.json
# Returns:
# CX_GOAL_EXC - Entity EPAY is not available
# in S/4HANA Public Cloud Learning Hub System
###
@salesOrderFromFile={{createSalesOrderFromFile.response.body.d.SalesOrder}}
###
# Read the created Sales Order
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder('{{salesOrderFromFile}}')
  ?$expand=to_Item,to_Item/to_ScheduleLine
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json

###
# @name createSalesOrder
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "SalesOrderType": "OR",
  "SalesOrganization": "{{$dotenv SalesOrganization}}",
  "DistributionChannel": "10",
  "OrganizationDivision": "00",
  "SalesOffice": "{{$dotenv SalesOffice}}",
  "SalesGroup": "{{$dotenv SalesGroup}}",
  "SoldToParty": "{{$dotenv SoldToParty}}",
  "PurchaseOrderByCustomer": "{{$dotenv PurchaseOrderByCustomer}}",
  "SalesOrderDate": "\/Date(1745588475000)\/",
  "PricingDate": "\/Date(1745588475000)\/",
  "RequestedDeliveryDate": "\/Date(1745588475000)\/",
  "CompleteDeliveryIsDefined": true,
  "to_Item": [
    {
      "SalesOrderItem": "000010",
      "Material": "{{$dotenv Material}}",
      "RequestedQuantity": "1",
      "RequestedQuantityUnit": "PC",
      "to_PricingElement": [
        {
           "ConditionType": "PMP0",
           "ConditionRateValue": "149.50"
        }
      ],
      "to_ScheduleLine": []
    }
  ],
  "to_Partner": [
    {
      "PartnerFunction": "SP",
      "Customer": "{{$dotenv SoldToParty}}",
      "to_Address": [
        {
          "OrganizationName1": "First Last",
          "CityName": "City",
          "PostalCode": "1234",
          "StreetName": "Rechnungsgasse",
          "HouseNumber": "10",
          "Country": "CH"
        }
      ]
    },
    {
      "PartnerFunction": "SH",
      "Customer": "{{$dotenv SoldToParty}}",
      "to_Address": [
        {
          "OrganizationName1": "First Last",
          "CityName": "City",
          "PostalCode": "1234",
          "StreetName": "Lieferstraße",
          "HouseNumber": "10",
          "Country": "CH"
        }
      ]
    }
  ],
  "to_Text": [
    {
      "Language": "EN",
      "LongTextID": "TX01",
      "LongText": "{{$dotenv LongText}}"
    }
  ]
}

###
#@salesOrder={{createSalesOrder.response.body.d.SalesOrder}}
@salesOrder={{$dotenv SalesOrder}}
###
# Read the created Sales Order
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder('{{salesOrder}}')
  ?$expand=to_Item,to_Item/to_ScheduleLine,to_Item/to_PricingElement,to_Partner,to_Partner/to_Address,to_PricingElement
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
