# https://api.sap.com/api/API_SERVICE_ORDER_SRV/overview
# Communication Scenario
# Service Order OData Integration (SAP_COM_0350)
# Service - Repair Order Integration (SAP_COM_0742)
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/{{$dotenv ServiceOrderQuery}}
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/A_ServiceOrder
  ?$inlinecount=allpages
  &$top=10
  &$expand=to_Item,to_Item/to_Confirmation,to_Item/to_PricingElement,to_Item/to_ReferenceObject,to_Item/to_SrvcOrdItemUserStatus,to_Item/to_Appointment,to_Item/to_Duration,to_Item/to_ProductReferenceObject,to_Item/to_Partner,to_Item/to_Partner/to_Address,to_Item/to_Text,to_ReferenceObject,to_Appointment
  &$orderby=ServiceOrder desc
  #&$filter=ServiceOrder eq '{{$dotenv ServiceOrder}}'
  #&$filter=ServiceOrderIsReleased eq 'X' and ServiceOrderIsCompleted eq '' and ServiceOrderIsRejected eq '' and SalesOrganization eq '{{$dotenv SalesOrganization}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/A_ServiceOrderItem
  ?$select=ServiceOrder,ServiceOrderItem,ServiceOrderItemIsReleased,to_ReferenceObject/ServiceOrder,to_ReferenceObject/ServiceOrderItem,to_ReferenceObject/ServiceReferenceEquipment,to_ReferenceObject/ServiceRefFunctionalLocation,to_ReferenceObject/SrvcRefObjIsMainObject
  &$expand=to_ReferenceObject
  &$filter=ServiceOrder eq '{{$dotenv ServiceOrder}}' and ServiceOrderItem eq '{{$dotenv ServiceOrderItem}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/A_ServiceOrder('{{$dotenv ServiceOrder}}')
  ?$expand=to_ReferenceObject
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/A_ServiceOrder
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name simulateSalesOrder
PATCH {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SERVICE_ORDER_SRV/A_ServiceOrder('{{$dotenv ServiceOrder}}')
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "ServiceOrderDescription": "Maintain Machine - 2025-09-29"
}

###
{
  "FSMServiceCall": "364"
}
