### Cloud: https://api.sap.com/api/API_SALES_ORDER_SIMULATION_SRV/overview
### OnPrem: https://api.sap.com/api/OP_API_SALES_ORDER_SIMULATION_SRV_0001/overview

### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/A_SalesOrderSimulation
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name simulateSalesOrder
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/A_SalesOrderSimulation
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "SalesOrderType": "OR",
  "SalesOrganization": "1010",
  "DistributionChannel": "10",
  "OrganizationDivision": "00",
  "SoldToParty": "10100003",
  "PurchaseOrderByCustomer": "PO-GROUP-88",
  "SalesOrderDate": "\/Date(1738678316000)\/",
  "PricingDate": "\/Date(1738678316000)\/",
  "RequestedDeliveryDate": "\/Date(1738678316000)\/",
  "ShippingCondition": "01",
  "CompleteDeliveryIsDefined": true,
  "to_Item": [
    {
      "SalesOrder": "10",
      "SalesOrderItem": "10",
      "Material": "TG11",
      "RequestedQuantity": "100",
      "RequestedQuantityUnit": "PC",
      "to_PricingElement": [],
      "to_ScheduleLine": []
    }
  ]
}

### With .env parameters
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_SALES_ORDER_SIMULATION_SRV/A_SalesOrderSimulation
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "SalesOrderType": "OR",
  "SalesOrganization": "{{$dotenv SalesOrganization}}",
  "DistributionChannel": "10",
  "OrganizationDivision": "00",
  "SoldToParty": "{{$dotenv SoldToParty}}",
  "PurchaseOrderByCustomer": "{{$dotenv PurchaseOrderByCustomer}}",
  "SalesOrderDate": "\/Date(1738678316000)\/",
  "PricingDate": "\/Date(1738678316000)\/",
  "RequestedDeliveryDate": "\/Date(1738678316000)\/",
  "CompleteDeliveryIsDefined": true,
  "to_Item": [
    {
      "SalesOrderItem": "10",
      "Material": "{{$dotenv Material}}",
      "RequestedQuantity": "21",
      "RequestedQuantityUnit": "PC",
      "to_PricingElement": [],
      "to_ScheduleLine": []
    }
  ]
}