### Cloud: https://api.sap.com/api/sap-s4-CE_APS_COM_CA_A4C_ODATA_0001-v1/overview
### Communication Scenario:
### Cloud Integration Automation Integration (SAP_COM_0A31)
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/
# S/4HANA Public Cloud System provided by SAP Learning Hub does only support certificate based authentication
# So I use my SAP Passport to access the system. That needs to be configured according to:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client --> SSL Client Certificates
# 
# Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/CommunicationArrangements
    ?$top=50
    &$count=true
    &$expand=*
    &$filter=startswith(Name,'GRP')
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createCommunicationArrangement
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/CommunicationArrangements
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0A48",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0A48"
}
### Try with $batch using JSON (https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_BatchRequest)
# "The server is refusing to process the request because the entity has an unsupported format
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "requests": [
    {
        "id": "1",
        "atomicityGroup": "group1",
        "method": "post",
        "url": "/CommunicationArrangements",
        "body": {
            "CommunicationScenarioID": "SAP_COM_0008",
            "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
            "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0008"
        }
    }
  ]
}
### https://docs.oasis-open.org/odata/odata/v4.01/csprd02/part1-protocol/odata-v4.01-csprd02-part1-protocol.html#sec_BatchRequests
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0106",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0106"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0109",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0109"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0353",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0353"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0466",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0466"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0053",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0053"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0164",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0164"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0118",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0118"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0117",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0117"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
###
# 
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0008",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0008"
}

--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
###
# ABAP Runtime error 'BEHAVIOR_ILLEGAL_STATEMENT'
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0102",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0102"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
###
# ABAP Runtime error 'BEHAVIOR_ILLEGAL_STATEMENT'
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0120",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0120"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
###
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http 
Content-Transfer-Encoding:binary

POST CommunicationArrangements HTTP/1.1
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0113",
    "CommunicationSystemID": "{{$dotenv s4hana_CommunicationSystemID}}",
    "Name": "{{$dotenv s4hana_ComArrNamePrefix}}_SAP_COM_0113"
}
--batch_36522ad7-fc75-4b56-8c71-56071383e77b--