### Cloud: https://api.sap.com/api/sap-s4-CE_APS_COM_CA_A4C_ODATA_0001-v1/overview
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/CommunicationArrangements
    ?$top=50
    &$count=true
    &$expand=*
    &$filter=startswith(Name,'GRP')
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createCommunicationArrangement
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/CommunicationArrangements
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0164",
    "CommunicationSystemID": "COM_SYS_GROUP_{{$dotenv s4hana_group_id}}",
    "Name": "GRP{{$dotenv s4hana_group_id}}_SAP_COM_0164"
}
###
# @name createCommunicationArrangement2
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/CommunicationArrangements
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0109",
    "CommunicationSystemID": "COM_SYS_GROUP_{{$dotenv s4hana_group_id}}",
    "Name": "GRP{{$dotenv s4hana_group_id}}_SAP_COM_0109"
}
### Try with $batch using JSON (https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_BatchRequest)
# "The server is refusing to process the request because the entity has an unsupported format
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "requests": [
    {
        "id": "2",
        "atomicityGroup": "group1",
        "method": "post",
        "url": "/CommunicationArrangements",
        "body": {
            "CommunicationScenarioID": "SAP_COM_0008",
            "CommunicationSystemID": "COM_SYS_GROUP_{{$dotenv s4hana_group_id}}",
            "Name": "GRP{{$dotenv s4hana_group_id}}_SAP_COM_0008"
        }
    }
  ]
}
### https://docs.oasis-open.org/odata/odata/v4.01/csprd02/part1-protocol/odata-v4.01-csprd02-part1-protocol.html#sec_BatchRequests
# Text hidden for information disclosure. See SAP Gateway Error Log, Message Monitoring Fiori App or ADT Feed Reader for details
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/aps_com_ca_a4c_odata/srvd_a2x/sap/aps_com_ca_a4c_odata/0001/$batch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: multipart/mixed; boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b

--batch_36522ad7-fc75-4b56-8c71-56071383e77b
Content-Type: application/http

POST /CommunicationArrangements
Content-Type: application/json

{
    "CommunicationScenarioID": "SAP_COM_0008",
    "CommunicationSystemID": "COM_SYS_GROUP_{{$dotenv s4hana_group_id}}",
    "Name": "GRP{{$dotenv s4hana_group_id}}_SAP_COM_0008"
}

--batch_36522ad7-fc75-4b56-8c71-56071383e77b--
