### Cloud: https://api.sap.com/api/sap-s4-CE_BILLINGDOCUMENT_0001-v1/overview
### OnPrem: 
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
# @name billingDocuments
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/BillingDocument
  ?$top=10
  &$expand=_Item($expand=_ItemPartner),*
  &$filter=LastChangeDateTime gt 2026-01-08T00:00:00Z
  #&$filter=PaymentMethod eq 'X'
  &$orderby=BillingDocument desc
  &$count=true
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Read first Billing Document to Variable
@billingDocument={{billingDocuments.response.body.value.0.BillingDocument}}
###
# @name billingDocumentRequest
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/BillingDocument/{{billingDocument}}
  ?$expand=_Item($expand=_ItemPartner),*
  &sap-language=DE
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_billingdocument/srvd_a2x/sap/billingdocument/0001/BillingDocument/SAP__self.CreateFromSDDocument
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "_Reference": [
    {
      "SDDocument": "{{$dotenv DeliveryDocument}}"
    }
  ]
}