### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/C_BEHQUEUEDATA_CDS/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/C_BEHQUEUEDATA_CDS/I_BusObjects
  ?$filter=SAPObjectTaskCode eq 'Created'
  &$inlinecount=allpages
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
