# ABAP Developer Trial 2022
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_bank/srvd_a2x/sap/bank/0002/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_bank/srvd_a2x/sap/bank/0002/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_bank/srvd_a2x/sap/bank/0002/Bank
  ?$top=10
  &$skip=0
  &$count=true
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_bank/srvd_a2x/sap/bank/0002/BankAddress
  ?$top=10
  &$count=true
  &$expand=*
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
