### SAP_COM_0516
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CIMV2_SI_BULK_EXTRACT_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CIMV2_SI_BULK_EXTRACT_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
