### Cloud: https://api.sap.com/api/ELECTRONICDOCFILE_0001/overview
### S/4HANA Cloud - SAP_COM_0703
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_electronicdocfile/srvd_a2x/sap/electronicdocfile/0001/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_electronicdocfile/srvd_a2x/sap/electronicdocfile/0001/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
# @name electronicDocFile
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_electronicdocfile/srvd_a2x/sap/electronicdocfile/0001/ElectronicDocFile
  ?$top=10
  &$count=true
  &$orderby=ElectronicDocLastChangeDate desc, ElectronicDocLastChangeTime desc
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json