# Cloud: https://api.sap.com/api/CE_PRODUCT_0002/overview
# SAP_COM_0009
# OnPrem: https://api.sap.com/api/OP_PRODUCT_0002/overview
# Sandbox
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/Product
  ?$count=true
  &$top=10
#  &$filter=ProductType eq 'KMAT'
  &$expand=_ProductDescription(),_ProductSales(),_ProductSalesDelivery($expand=_ProdSalesDeliverySalesTax())
  # $expand=*
  #_ProductChangeMaster(),_ProductEWMWarehouse(),_ProductPlant(),_ProductProcurement(),_ProductQualityManagement()
  #,_ProductStorage(),_ProductUnitOfMeasure(),_ProductValuation()
# 
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/Product
  ?$top=10
  &$filter=Product eq '{{$dotenv Product}}'
#  &$filter=LastChangeDateTime gt 2024-10-08T00:00:00Z
  &$count=true
#  &$expand=_ProductSalesDelivery,_ProductPlant($expand=*)
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/ProductPlantMRP
  ?$top=10
  &$count=true
  &$expand=*
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/ProductDescription
  ?$top=10
  &$count=true
  &$expand=*
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/ProductPlantStorageLocation
  ?$top=10
  &$count=true
  &$filter=Plant eq '{{$dotenv Plant}}' and Product eq '{{$dotenv Product}}'
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/Product('{{$dotenv product}}')
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json

### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
###
# @name createProduct
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0002/Product
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
X-CSRF-Token: {{CSRF}}
Content-Type: application/json

{
  "Product": "BIKE-GRP01-003",
  "IndustrySector": "M",
  "ProductType": "FERT",
  "GrossWeight": 20.000,
  "WeightUnit": "KG",
  "WeightISOUnit": "KGM",
  "ProductGroup": "L004",
  "BaseUnit": "ST",
  "BaseISOUnit": "PCE",
  "ItemCategoryGroup": "NORM",
  "NetWeight": 19.500,
  "_ProductDescription": [
        {
            "Product": "TE210921_1",
            "Language": "EN",
            "ProductDescription": "BIKE-GRP01-003"
        }
  ]
}