### Cloud: https://api.sap.com/api/CE_PURCHASEORDER_0001/overview
### OnPrem: 

###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/
APIKey: {{$dotenv apikey}}
Accept: application/json
###
### Returns:
### The entity A_PURCHASEORDERPARTNER_2 can only be accessed by navigation or expand
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrderPartner
  ?$top=10
  &$count=true
APIKey: {{$dotenv apikey}}
Accept: application/json
### S/4HANA Cloud
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrder
  ?$top=1
  &$count=true
  &$orderby=PurchaseOrder desc
  #&$filter=PurchaseOrderSubtype eq ''
  &$filter=PurchaseOrder eq '4501014184'
  # &$expand=_PurchaseOrderItem($expand=_DeliveryAddress(),_PurchaseOrder(),_PurchaseOrderInvoicingPlan(),_PurchaseOrderItemNote(),_PurchaseOrderScheduleLineTP(),_PurOrdAccountAssignment(),_PurOrdPricingElement()),_PurchaseOrderNote($expand=*),_PurchaseOrderPartner($expand=*),_SupplierAddress($expand=*)
  &$expand=_PurchaseOrderPartner,_SupplierAddress,_PurchaseOrderItem($expand=_DeliveryAddress)
  #_PurchaseOrderItem,_PurchaseOrderPartner,_SupplierAddress,_PurchaseOrderNote
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/
X-CSRF-Token: Fetch
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
### Read Token to Variable
@CSRF={{getCSRF.response.headers.x-csrf-token}}
### Create Purchase Order for Material NL001
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: application/json
Accept: application/json

< ./PURCHASEORDER_0001-NL001.json
### Create Purchase Order with two items
POST {{$dotenv s4hanahost}}/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrder
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
X-CSRF-Token: {{CSRF}}
Content-Type: application/json
Accept: application/json

< ./PURCHASEORDER_0001-two-items.json