#
# https://github.com/gregorwolf/ZAPI_USER_NAME
#
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/ZAPI_USER_NAME_SRV/$metadata
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/ZAPI_USER_NAME_SRV/
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
Accept: application/json
### Test if SAP Client can be set via Header
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/ZAPI_USER_NAME_SRV/UserDetailsSet
Authorization: Basic {{$dotenv s4hana_username}}:{{$dotenv s4hana_password}}
sap-client: 001
Accept: application/json