### https://api.sap.com/api/salesquote/overview
GET {{$dotenv host}}/sap/c4c/odata/v1/c4codataapi/SalesQuoteCollection
  ?$top=10
  &$inlinecount=allpages
  &$expand=SalesQuoteItem,SalesQuoteReference
  &$filter=ID eq '4000003267'
  #&$filter=ProcessingTypeCode ne 'ZAG'
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json
###
# @name createSalesQuote
POST {{$dotenv host}}/sap/c4c/odata/v1/c4codataapi/SalesQuoteCollection
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json
Content-Type: application/json

{
  "ProcessingTypeCode": "ZRG",
  "SalesUnitPartyID": "1010",
  "DistributionChannelCode": "10",
  "DivisionCode": "00",
  "BuyerPartyID": "{{$dotenv BuyerPartyID}}",
  "RequestedFulfillmentStartDateTime": "2025-05-28T00:00:00Z",
  "TimeZoneCode": "GMTUK",
  "ValidToDate": "\/Date(1767139200000)\/",
  "z_Anfragedatum_KUT": "\/Date(1748217600000)\/",
  "SalesQuoteItem": [
    {
      "ItemID": "100",
      "ProductInternalID": "{{$dotenv ProductInternalID}}",
      "zk_PositionReference_Quote_KUT": "1.3.4",
      "Quantity": "1.00000000000000",
      "QuantityMeasureUnitCode": "ZPC"
    }
  ],
  "SalesQuoteReference": [
    {
      "RelationshipRoleCode": "1",
      "ID": "{{$dotenv opportunity}}",
      "TypeCode": "72"
    }
  ]
}
###
@salesQuoteLocation={{createSalesQuote.response.headers.Location}}
@salesQuoteID=4000003302
#{{createSalesQuote.response.body.d.results.ID}}
###
GET {{salesQuoteLocation}}
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json
###
GET {{$dotenv host}}/sap/c4c/odata/v1/c4codataapi/SalesQuoteCollection
  ?$top=10
  &$inlinecount=allpages
  &$expand=SalesQuoteItem,SalesQuoteReference
  &$filter=ID eq '{{salesQuoteID}}'
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json