### https://api.sap.com/api/salesquote/overview
GET {{$dotenv host}}/sap/c4c/odata/v1/c4codataapi/SalesQuoteCollection
  ?$top=10
  &$inlinecount=allpages
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json