# https://api.sap.com/api/ECPersonalInformation/overview
### PerPersonal
GET {{$dotenv sf_base_url}}/odata/v2/PerPersonal
  ?$top=5
  &$inlinecount=allpages
  &$filter=nationality eq 'DEU'
  &$expand=localNavDEU
apikey: {{$dotenv apikey}}
Accept: application/json
