###
# @name readImports
GET {{$dotenv workist_api}}master-data/imports
  ?page_size=10
Authorization:Bearer {{$dotenv workist_token}}
###
@importId={{readImports.response.body.$.items.0.import_id}}
@input_file_url={{readImports.response.body.$.items.0.input_file_url}}
###
# @name readImport
GET {{$dotenv workist_api}}master-data/imports/{{importId}}
Authorization:Bearer {{$dotenv workist_token}}
###
GET {{input_file_url}}
#Authorization:Bearer {{$dotenv workist_token}}
