### https://api.workist.com/v1/swagger/#/
GET https://api.workist.com/v1/swagger.json
###
# @name readOrders
GET {{$dotenv workist_api}}orders
  ?page_size=10
  &finished=true
  &channel=f721e73a-3f3e-407b-938f-7ce7754c4b19
Authorization: Bearer {{$dotenv workist_token}}
###
@orderId={{readOrders.response.body.$.items.0.id}}
###
# @name readOrder
GET {{$dotenv workist_api}}orders/{{orderId}}
  ?channel=f721e73a-3f3e-407b-938f-7ce7754c4b19
Authorization:Bearer {{$dotenv workist_token}}
