### Requires REST Client for VS Code
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###
### Edit your settings.json and add the configuration from rest-client-config.json for local tests

### Read Pictures
# curl http://localhost:4004/odata/v4/admin/Documents | jq
# @name readDocuments
GET http://localhost:4004/odata/v4/admin/Documents
Authorization: Basic admin:
###
@documentGuid = {{readDocuments.response.body.$.value[0].ID}}
### Read PDF
GET http://localhost:4004/odata/v4/admin/Documents({{documentGuid}})/content
Authorization: Basic admin:

### Create Picture with mediatype
# curl -X POST http://localhost:4004/odata/v4/admin/Documents -H "Accept: application/json" -H "Content-Type: application/json" --data '{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" }'
POST http://localhost:4004/odata/v4/admin/Documents
Authorization: Basic admin:
Accept: application/json
Content-Type: application/json

{ 
  "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9",
  "mediatype": "image/png",
  "filename": "Test.png"
}

### Create Picture without mediatype
POST http://localhost:4004/odata/v4/admin/Documents
Authorization: Basic admin:
Accept: application/json
Content-Type: application/json

{ 
  "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9"
}

### Upload Binary PNG
# curl -X PUT "http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content" -H "image/png" --data-binary @./srv/tests/Test.png
PUT http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content
Authorization: Basic admin:
Content-Type: image/png

< ./Test.png

### Create Picture in one request
# curl -v http://localhost:4004/odata/v4/admin/Documents -F file0=@./srv/tests/Test.png json='{ "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9" }' 
# This results in the following eror:
# {"error":{"code":null,"message":"No payload deserializer available for resource kind 'ENTITY' and mime type 'multipart/form-data'"}}* Rebuilt URL to: json= "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9"

### Read Binary
# curl "http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content"
GET http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content
Authorization: Basic admin:

### Read Binary OData V2
# curl "http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/$value"
GET http://localhost:4004/v2/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/$value
Authorization: Basic admin:

### Delete Image
# curl -X DELETE "http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)"
DELETE http://localhost:4004/odata/v4/admin/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)
Authorization: Basic admin:

### Test with Excel document
@excelID=da07ae51-d0d3-41e7-a737-2555a213e5a0
POST http://localhost:4004/odata/v4/admin/Documents
Authorization: Basic admin:
Accept: application/json
Content-Type: application/json

{ 
  "ID": "{{excelID}}",
  "mediatype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "filename": "Test.xlsx"
}

###
PUT http://localhost:4004/odata/v4/admin/Documents({{excelID}})/content
Authorization: Basic admin:
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./Test.xlsx


### Read Binary
GET http://localhost:4004/odata/v4/admin/Documents({{excelID}})/content
Authorization: Basic admin:

### Read Binary OData V2
GET http://localhost:4004/v2/admin/Documents({{excelID}})/$value
Authorization: Basic admin:

###
DELETE http://localhost:4004/odata/v4/admin/Documents({{excelID}})
Authorization: Basic admin:
