### Read BooksAnalytics
GET http://localhost:4004/odata/v4/analytics/
Authorization: Basic admin:
### Read BooksAnalytics
GET http://localhost:4004/odata/v4/analytics/$metadata
Authorization: Basic admin:
### Read BooksAnalytics
http://localhost:4004/odata/v4/analytics/BooksAnalytics
  ?$count=true
  //&$expand=author,currency
  &$compute=price mul stock as StockValue
  # price mul author/ID as StockValueInHundreds
Authorization: Basic admin:
### Read BooksAnalytics
http://localhost:4004/v2/analytics/BooksAnalytics
Authorization: Basic admin:
### Group by with navigation attribute
http://localhost:4004/odata/v4/order/Orders
  ?$count=true
  &$apply=groupby((orderstatus_code,orderstatus/name),aggregate($count as childCount,total with sum as TotalValue))
Authorization: Basic admin:
### Filter and Group by with navigation attribute
http://localhost:4004/odata/v4/order/Orders
  ?$count=true
  &$apply=filter(deliverystatus_code eq 'N')/groupby((orderstatus_code,orderstatus/name),aggregate($count as childCount,total with sum as TotalValue))
  #&$apply=groupby((orderstatus/name),aggregate($count as childCount,total with sum as TotalValue))
Authorization: Basic admin:
# Lean Draft:     "message": "invalid column name: ORDERSTATUS: line 1 col 45 (at pos 44)"
#  SELECT count ( 1 ) AS "$count" FROM (SELECT orderstatus, count ( 1 ) AS childCount, sum ( total ) AS TotalValue 
# FROM localized_AdminService_Orders ALIAS_1 GROUP BY orderstatus.code)
# Standard:     "message": "invalid column name: ACTIVE.TOTAL: line 1 col 65 (at pos 64)"
# SELECT b.code AS "b_code", count ( 1 ) AS "a_childCount", sum ( active.total ) AS "a_TotalValue" 
# FROM localized_AdminService_Orders a LEFT JOIN localized_AdminService_Orderstatuses b ON ( b.code = a.orderstatus_code ) 
# GROUP BY a.orderstatus.code ORDER BY a.orderstatus.code ASC LIMIT 1000  with parameters ('LOCALE' = 'en')
### Total Stock
http://localhost:4004/analytics/BooksAnalytics
  ?$count=true
  &$apply=groupby((authorID),aggregate($count as childCount,stock with sum as TotalStock))
Authorization: Basic admin:
### Total Stock grouped by author/name
# Results in: invalid column name: AUTHOR: line 1 col 45 (at pos 44)
# SQL: SELECT count ( 1 ) AS "$count" FROM (SELECT author, count ( 1 ) AS childCount, sum ( stock ) AS TotalStock FROM localized_AnalyticsService_BooksAnalytics ALIAS_1 GROUP BY author.name)
http://localhost:4004/analytics/BooksAnalytics
  ?$count=true
  &$apply=groupby((author/name),aggregate($count as childCount,stock with sum as TotalStock))
Authorization: Basic admin:
### Total Stock grouped by author/name without $count
# Works
http://localhost:4004/analytics/BooksAnalytics
  ?$apply=groupby((author/name),aggregate($count as childCount,stock with sum as TotalStock))
Authorization: Basic admin:
### Total Books per Author
http://localhost:4004/analytics/BooksAnalytics
  ?$apply=groupby((author/name,currency/name),aggregate(count with sum as TotalBooks))
  &$orderby=TotalBooks desc
Authorization: Basic admin:

### Read BooksAnalytics - 
http://localhost:4004/analytics/BooksAnalytics
  ?$apply=groupby((authorID),aggregate(stock%20with%20sum%20as%20TotalStock))
  &$select=authorID
  &$skip=0
  &$top=100
Authorization: Basic admin:
