### Read BooksAnalytics
http://localhost:4004/admin/BooksAnalytics
  ?$count=true
  &$expand=author,currency
Authorization: Basic admin:

### Read BooksAnalytics
http://localhost:4004/v2/admin/BooksAnalytics
Authorization: Basic admin:

### Total Stock
http://localhost:4004/admin/BooksAnalytics
  ?$count=true
  &$apply=groupby((authorID),aggregate($count as childCount,stock with sum as TotalStock))
Authorization: Basic admin:

### Total Books per Author
http://localhost:4004/admin/BooksAnalytics
  ?$apply=groupby((author/name,currency/name),aggregate(count with sum as TotalBooks))
  &$orderby=TotalBooks desc
Authorization: Basic admin:

### Read BooksAnalytics - 
http://localhost:4004/admin/BooksAnalytics
  ?$apply=groupby((authorID),aggregate(stock%20with%20sum%20as%20TotalStock))
  &$select=authorID
  &$skip=0
  &$top=100
Authorization: Basic admin:
