### ERP

### metadata
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CV_ATTACHMENT_SRV/$metadata
x-sap-security-session: disabled
### Read GetAttachmentCount
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CV_ATTACHMENT_SRV/GetAttachmentCount
  ?ObjectType='{{BusinessObjectTypeName}}'
  &ObjectKey='{{$dotenv material}}'
  &SemanticObjectType=''
Accept: application/json
### GetAllOriginals
# @name erpGetAllOriginals
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CV_ATTACHMENT_SRV/GetAllOriginals
  ?ObjectType='{{BusinessObjectTypeName}}'
  &ObjectKey='{{$dotenv material}}'
  &SemanticObjectType=''
Accept: application/json
Accept-Language: en
### Read result to variable
@ERPDocumenttype={{erpGetAllOriginals.response.body.d.results[0].Documenttype}}
@ERPDocumentnumber={{erpGetAllOriginals.response.body.d.results[0].Documentnumber}}
@ERPApplicationId={{erpGetAllOriginals.response.body.d.results[0].ApplicationId}}
@ERPFileId={{erpGetAllOriginals.response.body.d.results[0].FileId}}
###
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/CV_ATTACHMENT_SRV/OriginalContentSet(Documenttype='{{ERPDocumenttype}}',Documentnumber='{{ERPDocumentnumber}}',Documentpart='',Documentversion='',ApplicationId='{{ERPApplicationId}}',FileId='{{ERPFileId}}')/$value

### S/4HANA Original
# BUS1001006 = Material
@BusinessObjectTypeName=BUS1001006
### metadata
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/$metadata
x-sap-security-session: disabled

### Read GetAttachmentCount
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/GetAttachmentCount
  ?BusinessObjectTypeName='{{BusinessObjectTypeName}}'
  &LinkedSAPObjectKey='{{$dotenv material}}'
  &SemanticObject=''
Accept: application/json

### Get CSRF Token
# @name getCSRF
HEAD {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV
X-CSRF-Token: Fetch
### Read Token to Variable
@csrf={{getCSRF.response.headers.x-csrf-token}}

### Create Attachment in GOS
# @name createAttachment
POST {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/AttachmentContentSet
X-CSRF-Token: {{csrf}}
Accept-Language: en
Accept: application/json
Content-Type: image/png
Slug: Test.png
BusinessObjectTypeName: {{BusinessObjectTypeName}}
LinkedSAPObjectKey: {{$dotenv material}}

< ./Test.png

### GetAllOriginals
# @name getAllOriginals
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/GetAllOriginals
  ?BusinessObjectTypeName='{{BusinessObjectTypeName}}'
  &LinkedSAPObjectKey='{{$dotenv material}}'
  &SemanticObject=''
Accept: application/json
Accept-Language: en

### Read Token to Variable
@DMSDocumentInfoRecordDocType={{getAllOriginals.response.body.d.results[0].DocumentInfoRecordDocType}}
@DMSDocumentInfoRecordDocNumber={{getAllOriginals.response.body.d.results[0].DocumentInfoRecordDocNumber}}
@DMSLogicalDocument={{getAllOriginals.response.body.d.results[0].LogicalDocument}}
@DMSArchiveDocumentID={{getAllOriginals.response.body.d.results[0].ArchiveDocumentID}}
@DMSLinkedSAPObjectKey={{getAllOriginals.response.body.d.results[0].LinkedSAPObjectKey}}
@DMSBusinessObjectTypeName={{getAllOriginals.response.body.d.results[0].BusinessObjectTypeName}}

### Read created document Metadata - is not implemented
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/AttachmentContentSet(DocumentInfoRecordDocType='{{DMSDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{DMSDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{DMSLogicalDocument}}',ArchiveDocumentID='{{DMSArchiveDocumentID}}',LinkedSAPObjectKey='{{DMSLinkedSAPObjectKey}}',BusinessObjectTypeName='{{DMSBusinessObjectTypeName}}')
Accept: application/json
### Read created document Content
GET {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/AttachmentContentSet(DocumentInfoRecordDocType='{{DMSDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{DMSDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{DMSLogicalDocument}}',ArchiveDocumentID='{{DMSArchiveDocumentID}}',LinkedSAPObjectKey='{{DMSLinkedSAPObjectKey}}',BusinessObjectTypeName='{{DMSBusinessObjectTypeName}}')/$value
### Delete created document
# Seems that it only delete the reference
DELETE {{$dotenv s4hanahost}}/sap/opu/odata/sap/API_CV_ATTACHMENT_SRV/AttachmentContentSet(DocumentInfoRecordDocType='{{DMSDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{DMSDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{DMSLogicalDocument}}',ArchiveDocumentID='{{DMSArchiveDocumentID}}',LinkedSAPObjectKey='{{DMSLinkedSAPObjectKey}}',BusinessObjectTypeName='{{DMSBusinessObjectTypeName}}')
X-CSRF-Token: {{csrf}}
Accept: application/json

###
GET http://localhost:4004/odata/v2/API_CV_ATTACHMENT_SRV/$metadata
###
GET http://localhost:4004/odata/v2/API_CV_ATTACHMENT_SRV/
Accept: application/json
### Read GetAttachmentCount via V4 endpoint
GET http://localhost:4004/API_CV_ATTACHMENT_SRV/GetAttachmentCount(BusinessObjectTypeName='{{BusinessObjectTypeName}}',LinkedSAPObjectKey='{{$dotenv material}}',SemanticObject='')
Accept: application/json

### Returns:
{
  "@odata.context": "$metadata#AttachmentContentService.API_CV_ATTACHMENT_SRV_AttachmentsCount",
  "AttachmentCount": 2
}

### Read GetAttachmentCount via V2 endpoint
GET http://localhost:4004/odata/v2/API_CV_ATTACHMENT_SRV/GetAttachmentCount
  ?BusinessObjectTypeName='{{BusinessObjectTypeName}}'
  &LinkedSAPObjectKey='{{$dotenv material}}'
  &SemanticObject=''
Accept: application/json

### Returns:
{
  "d": {
    "GetAttachmentCount": {
      "AttachmentCount": 0
    }
  }
}
### Read GetAttachmentCount via V4 endpoint
GET http://localhost:4004/API_CV_ATTACHMENT_SRV/GetAllOriginals(BusinessObjectTypeName='{{BusinessObjectTypeName}}',LinkedSAPObjectKey='{{$dotenv material}}',SemanticObject='')
Accept: application/json
### Read GetAllOriginals via V2 endpoint
# @name capGetAllOriginals
GET http://localhost:4004/odata/v2/API_CV_ATTACHMENT_SRV/GetAllOriginals
  ?BusinessObjectTypeName='{{BusinessObjectTypeName}}'
  &LinkedSAPObjectKey='{{$dotenv material}}'
  &SemanticObject=''
Accept: application/json

### Read result to variable
@CAPDocumentInfoRecordDocType={{capGetAllOriginals.response.body.d.results[0].DocumentInfoRecordDocType}}
@CAPDocumentInfoRecordDocNumber={{capGetAllOriginals.response.body.d.results[0].DocumentInfoRecordDocNumber}}
@CAPLogicalDocument={{capGetAllOriginals.response.body.d.results[0].LogicalDocument}}
@CAPArchiveDocumentID={{capGetAllOriginals.response.body.d.results[0].ArchiveDocumentID}}
@CAPLinkedSAPObjectKey={{capGetAllOriginals.response.body.d.results[0].LinkedSAPObjectKey}}
@CAPBusinessObjectTypeName={{capGetAllOriginals.response.body.d.results[0].BusinessObjectTypeName}}
### Read created document via V2 endpoint
GET http://localhost:4004/odata/v2/API_CV_ATTACHMENT_SRV/AttachmentContentSet(DocumentInfoRecordDocType='{{CAPDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{CAPDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{CAPLogicalDocument}}',ArchiveDocumentID='{{CAPArchiveDocumentID}}',LinkedSAPObjectKey='{{CAPLinkedSAPObjectKey}}',BusinessObjectTypeName='{{CAPBusinessObjectTypeName}}')/$value
### Read created document
GET http://localhost:4004/API_CV_ATTACHMENT_SRV/AttachmentContentSet(DocumentInfoRecordDocType='{{CAPDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{CAPDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{CAPLogicalDocument}}',ArchiveDocumentID='{{CAPArchiveDocumentID}}',LinkedSAPObjectKey='{{CAPLinkedSAPObjectKey}}',BusinessObjectTypeName='{{CAPBusinessObjectTypeName}}')/Content
