### 
GET http://localhost:4004/GWSAMPLE_BASIC/
Authorization: Basic admin:

### 
GET http://localhost:4004/GWSAMPLE_BASIC/BusinessPartnerSet
  ?$top=5
  &$select=BusinessPartnerID,CompanyName,WebAddress,EmailAddress,PhoneNumber,FaxNumber,LegalForm,CurrencyCode,BusinessPartnerRole,CreatedAt,ChangedAt
Authorization: Basic admin:
Accept: application/json
### 
GET http://localhost:4004/GWSAMPLE_BASIC/ContactSet
  ?$top=1
Authorization: Basic admin:
Accept: application/json
###
GET {{$dotenv saperp}}/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet
  ?$top=1
Authorization: Basic {{$dotenv saperpusername}}:{{$dotenv saperppassword}}
Accept: application/json
###
GET https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata
Authorization: Basic {{$dotenv es5username}}:{{$dotenv es5password}}
###
GET https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet
  ?$top=1
Authorization: Basic {{$dotenv es5username}}:{{$dotenv es5password}}
Accept: application/json

###
GET https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet
  ?$select=BusinessPartnerID,Address,CompanyName,WebAddress,EmailAddress,PhoneNumber,FaxNumber,LegalForm,CurrencyCode,BusinessPartnerRole,CreatedAt,ChangedAt
  &$top=10
  &$orderby=BusinessPartnerID%20asc
Authorization: Basic {{$dotenv es5username}}:{{$dotenv es5password}}
Accept: application/json

### Via sap-cf-proxy
GET http://localhost:5050/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet
  ?$top=1
Accept: application/json
