###
GET http://localhost:4004/odata/v4/directory/
Authorization: Basic bob:
###
GET http://localhost:4004/odata/v4/directory/$metadata
Authorization: Basic bob:
### Set Session
POST http://localhost:4004/odata/v4/directory/Session
Authorization: Basic bob:
Content-Type: application/json

{
  "directory": "B",
  "version": 1
}

### Set Session A1
PATCH http://localhost:4004/odata/v4/directory/Session('bob')
Authorization: Basic bob:
Content-Type: application/json

{
  "directory": "A",
  "version": 1
}
### Set Session B1
PATCH http://localhost:4004/odata/v4/directory/Session('bob')
Authorization: Basic bob:
Content-Type: application/json

{
  "directory": "B",
  "version": 1
}
###
GET http://localhost:4004/odata/v4/directory/Session
Authorization: Basic bob:
### Read data using $user attributes and setting one attribute in the before handler (which does not work)
GET http://localhost:4004/odata/v4/directory/Process
  ?$expand=processType
Authorization: Basic bob:
### Read data using $session attribute - results in invalid column name: $SESSION.VERSION
GET http://localhost:4004/odata/v4/directory/ProcessType
Authorization: Basic bob:
### Check if value set with SET 'VERSION' = '1' can be read using SESSION_CONTEXT('VERSION')
GET http://localhost:4004/odata/v4/directory/Version
Authorization: Basic bob:
