###
GET http://localhost:4004/document-management
Accept: application/json
###
GET http://localhost:4004/document-management/getRepositoryInfo()
Accept: application/json
###
GET http://localhost:4004/document-management/getFolderTree()
Accept: application/json
###
@folder=folder01
#@folder=folder02
@objectId=2GC3QQ42vEjGVIebr3nG58Ea1PUwPLFXbmQZgizVZos

###
GET http://localhost:4004/document-management/getChildren(folderName='{{objectId}}')
Accept: application/json

###
POST http://localhost:4004/document-management/createFolder
Accept: application/json
Content-Type: application/json

{
  "folderName": "{{folder}}"
}

### Create Picture without mediatype
POST http://localhost:4004/document-management/Documents
Authorization: Basic admin:
Accept: application/json
Content-Type: application/json

{ 
  "ID": "da07ae51-d0d3-41e7-a737-2555a213e5a9",
  "mediatype": "image/png",
  "filename": "Testö.png"
}

### Upload Binary PNG
PUT http://localhost:4004/document-management/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content
Authorization: Basic admin:
Content-Type: image/png

< ./Test.png

### Read Metadata
GET http://localhost:4004/document-management/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)
Authorization: Basic admin:
### Read Binary
GET http://localhost:4004/document-management/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)/content
Authorization: Basic admin:

### Delete Binary
DELETE http://localhost:4004/document-management/Documents(da07ae51-d0d3-41e7-a737-2555a213e5a9)
Authorization: Basic admin:
