### Endpoint for Excel V2
GET http://vhcalnplci.dummy.nodomain:4004/v2/catalog/

### Endpoint for Excel V4
GET http://vhcalnplci.dummy.nodomain:4004/catalog/

### Read Books via OData V2 like Excel does it
GET http://localhost:4004/v2/catalog/Books
Accept: application/atomsvc+xml,application/atom+xml

### Read Books via OData like Excel does it
GET http://localhost:4004/catalog/Books
Accept: application/atomsvc+xml,application/atom+xml

### Test Service from odata.org
GET https://services.odata.org/TripPinRESTierService/Airlines
Accept: application/atomsvc+xml,application/atom+xml

### Testing the corrected proxy 1.4.59 started via
### npm run start:forExcel

### OData V4 Endpoint - OK
GET http://localhost:4004/

### OData V2 Endpoint - returns:
### 'v2' is not an entity set, a singleton, an action import, or a function import
GET http://localhost:4004/v2/

### OData V4 Books - OK
GET http://localhost:4004/Books

### OData V2 Books - returns:
### 'v2' is not an entity set, a singleton, an action import, or a function import
GET http://localhost:4004/v2/Books
