### Read Books via OData V4 by littleadmin
GET http://localhost:4004/odata/v4/admin/Books?$top=10
Authorization: Basic littleadmin:

### Read Books via OData V2 by littleadmin
GET http://localhost:4004/v2/admin/Books?$top=10
Authorization: Basic littleadmin:
