###
GET http://localhost:4004/v2/admin/$metadata
Authorization: Basic admin:
###
GET http://localhost:4004/odata/v4/admin/$metadata
Authorization: Basic admin:
### Read Roles via OData V2
GET http://localhost:4004/v2/admin/Roles
Authorization: Basic admin:

### Read BusinessObjects assigned to Roles via OData V2
GET http://localhost:4004/v2/admin/Roles(ID=guid'1e50a05d-aa09-4bd2-b2a5-0d096adb7b8c',IsActiveEntity=true)/BusinessObjects
Authorization: Basic admin:

### Read Roles Expanded to  via OData V2
GET http://localhost:4004/v2/admin/Roles?$expand=BusinessObjects,Users
Authorization: Basic admin:
###
GET http://localhost:4004/odata/v4/admin/
Authorization: Basic admin:
### Read Roles via OData V4
GET http://localhost:4004/odata/v4/admin/Roles
Authorization: Basic admin:
###
PATCH http://localhost:4004/odata/v4/admin/Roles(ID=009bb7fa-43ef-4e4a-85b1-5a9ea692a5b6,IsActiveEntity=true)
Authorization: Basic admin:
Accept: application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language: en
Prefer: return=minimal
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true

{
  "description":"Role for Orders and Book"
}
### Read Roles Expanded to  via OData V4
GET http://localhost:4004/odata/v4/admin/Roles?$expand=BusinessObjects,Users
Authorization: Basic admin:

### Read User Details & try expand
GET http://localhost:4004/odata/v4/admin/Userdetails
  ?$expand=authorizations
Authorization: Basic admin:
### Read User Authorizations
GET http://localhost:4004/odata/v4/admin/Userdetails/authorizations
Authorization: Basic admin:
### Read User Authorizations directly
GET http://localhost:4004/odata/v4/admin/Authorizations
Authorization: Basic admin:
###
GET http://localhost:4004/odata/v4/admin/Authorizations
Authorization: Basic roleadmin:
###
GET http://localhost:4004/odata/v4/admin/Authorizations
Authorization: Basic booksadmin:
### Read Users
GET http://localhost:4004/odata/v4/admin/Users
Authorization: Basic admin:

### Read Users Expanded to via OData V4 - 
GET http://localhost:4004/odata/v4/admin/Users?$expand=employee,roles,address
Authorization: Basic admin:
### Read Employees Expanded to via OData V4 - 
GET http://localhost:4004/odata/v4/admin/Employees?$expand=users
Authorization: Basic admin:
### Read Users Expanded to via OData V2
### Results in:
### An error occurred during serialization of the entity collection. An error occurred during serialization of the entity with the following key(s): username: douglas. The provided data does not fit the type of the navigation property: address.
GET http://localhost:4004/v2/admin/Users?$expand=address
Authorization: Basic admin:

###
@roleID=009bb7fa-43ef-4e4a-85b1-5a9ea692a5b0
### Create new role using the draft dance
# @name createRole
POST http://localhost:4004/odata/v4/admin/Roles
Authorization: Basic admin:
Content-Type: application/json

{
  "ID": "{{roleID}}",
  "rolename": "",
  "description": "Description"
}

###
@location = {{createRole.response.headers.Location}}

###
GET http://localhost:4004/odata/v4/admin/{{location}}
Authorization: Basic admin:

###
PATCH http://localhost:4004/odata/v4/admin/{{location}}
Authorization: Basic admin:
Content-Type: application/json

{
  "rolename": "Test Draft 2",
  "description": ""
}

###
POST http://localhost:4004/odata/v4/admin/{{location}}/AdminService.draftPrepare
Authorization: Basic admin:
Content-Type: application/json

{"SideEffectsQualifier":""}

###
POST http://localhost:4004/odata/v4/admin/{{location}}/AdminService.draftActivate
Authorization: Basic admin:
Content-Type: application/json

{}

###
GET http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)
  ?$expand=DraftAdministrativeData
  // &$select=description
Authorization: Basic admin:
###
GET http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)
  ?$expand=DraftAdministrativeData
Authorization: Basic roleadmin:
### Edit role using the draft dance
# @name editRole
POST http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)/AdminService.draftEdit
Authorization: Basic admin:
Content-Type: application/json

{"PreserveChanges":false}

### Try to create a draft as another user
# Not Possible with PreserveChanges = true
POST http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)/AdminService.draftEdit
Authorization: Basic roleadmin:
Content-Type: application/json

{"PreserveChanges":true}

### Try to create a draft as another user
POST http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)/AdminService.draftEdit
Authorization: Basic roleadmin:
Content-Type: application/json

{"PreserveChanges":false}
###
@locationEdit = {{editRole.response.headers.Location}}
###
PATCH http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=false)
Authorization: Basic admin:
Content-Type: application/json

{
  "rolename": "Changes",
  "description": "Add description"
}
###
POST http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=false)/AdminService.draftPrepare
Authorization: Basic admin:
Content-Type: application/json

{"SideEffectsQualifier":""}

###
POST http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=false)/AdminService.draftActivate
Authorization: Basic admin:
Content-Type: application/json

{}

###
GET http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=false)
Authorization: Basic roleadmin:
###
GET http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)
Authorization: Basic admin:
### Delete Entity
DELETE  http://localhost:4004/odata/v4/admin/Roles(ID={{roleID}},IsActiveEntity=true)
Authorization: Basic admin:
