###
GET http://localhost:4004/temporal/
###
GET http://localhost:4004/temporal/$metadata
###
GET http://localhost:4004/temporal/Employees
###
GET http://localhost:4004/temporal/Employees
  ?$expand=jobs
###
GET http://localhost:4004/temporal/Employees
  ?$expand=jobs
  &sap-valid-to=date'2020-12-10'
#  &sap-valid-from=date'2016-01-01'
###
GET http://localhost:4004/temporal/WorkAssignments
###
GET http://localhost:4004/temporal/WorkAssignments
  ?sap-valid-at=date'2020-05-10'
###
GET http://localhost:4004/temporal/WorkAssignments
  ?sap-valid-to=date'2020-12-10'
#sap-valid-to: date'2020-12-10'
###
GET http://localhost:4004/temporal/WorkAssignments
  ?sap-valid-to=date'2021-01-01'
###
GET http://localhost:4004/temporal/WorkAssignments
  ?sap-valid-from=date'2016-01-01'
###
GET http://localhost:4004/temporal/WorkAssignments
  ?sap-valid-from=date'2021-01-01'
###
GET http://localhost:4004/temporal/WorkAssignments

###
GET http://localhost:4004/temporal/Department
### sap-valid-at must also be provided to return correct result
GET http://localhost:4004/temporal/WorkAssignmentsForKeyDate(keyDate=2021-01-01)/Set
  ?sap-valid-at=date'2021-01-01'
### works only if sap-valid-at is provided
GET http://localhost:4004/temporal/WorkAssignmentsForKeyDate(keyDate=2020-12-31)/Set
  ?sap-valid-at=date'2020-12-31'
