### SAP Cloud ALM ITSM API
###
### https://help.sap.com/docs/cloud-alm/apis/itsm-api
### https://api.sap.com/api/CALM_ITSM/overview
###
### Service instance must be created with the scope "$XSMASTERAPPNAME.calm-api.bsm.read" following:
### https://help.sap.com/docs/cloud-alm/setup-administration/enabling-sap-cloud-alm-api?locale=en-US

### Request Access Token
# @name requestAccessToken
POST {{$dotenv cloud_alm_token_endpoint}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv cloud_alm_itsm_api_clientid}}
&client_secret={{$dotenv cloud_alm_itsm_api_clientsecret}}
&grant_type=client_credentials
&response_type=token
### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
### Working APIs
###
GET {{$dotenv cloud_alm_api}}/api/calm-itsmapi/v1/supportcases/masterdata/components
    ?offset=0
    &limit=50
Authorization: Bearer {{access_token}}
###
GET {{$dotenv cloud_alm_api}}/api/calm-itsmapi/v1/supportcases/masterdata/landscapeObjects
    ?offset=0
    &limit=50
    &reporter={{$dotenv reporter}}
#    &searchText=
Authorization: Bearer {{access_token}}
### It doesn't make any sense to me that reporter and customerNumber are mandatory this API
### it should be enough to limit by customerNumber or nothing at all as the S-User is 
### maintained in the destination calm_itsm_support
GET {{$dotenv cloud_alm_api}}/api/calm-itsmapi/v1/supportcases/masterdata/contacts
    ?offset=0
    &limit=50
    &reporter={{$dotenv reporter}}
    &customerNumber={{$dotenv customerNumber}}
Authorization: Bearer {{access_token}}
### Not working APIs
###
### Response is empty but HTTP Status is 200
### Even with correct installationNumber
GET {{$dotenv cloud_alm_api}}/api/calm-itsmapi/v1/supportcases/cases/ids
    ?offset=0
    &limit=100
    &installationNumber={{$dotenv installationNumber}}
    &reporter={{$dotenv reporter}}
Authorization: Bearer {{access_token}}
### esponse is empty but HTTP Status is 200
GET {{$dotenv cloud_alm_api}}/api/calm-itsmapi/v1/supportcases/cases
    ?id=002075129400000473662025
    &reporter={{$dotenv reporter}}
Authorization: Bearer {{access_token}}
