name: release-mta-hana

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      # - name: Download XSA artifact
      #   uses: dawidd6/action-download-artifact@v6
      #   with:
      #     workflow: build-mta-hana.yml
      #     workflow_conclusion: success
      #     name: mta
      - name: Download CF artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-mta-cf.yml
          workflow_conclusion: success
          name: mta
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bookshop-demo-cf.mtar
          # files: |
          #   bookshop-demo-xsa.mtar
          #   bookshop-demo-cf.mtar
